### ISSUE TITLE
export texture | wrong color?

### ISSUE THREAD

**Issue by crazy6995** [DerPopo/UABE#10]
export texture2d resource to .tga & .png . 
 I got the .tga file but not correct color...  

unity 5.0

**Comment by crazy6995** [comment]
sorry for my bad english...

**Comment by DerPopo** [comment]
There will be some fixes for it but there still might be some bugs.

**Comment by 0x900x90** [comment]
Looks like new unity version uses DXT4 format sometimes. I made raw dump and imported them in PVRTexTool using raw wrapper. Got perfect result.

**Comment by DerPopo** [comment]
They added DXT1Crunched and DXT5Crunched (using https://github.com/richgel999/crunch ), there isn't anything about DXT4 in the enums though.

**Comment by 0x900x90** [comment]
You are right. I don't see DXT4 in enums.

**Comment by crazy6995** [comment]
thank for your guys help.

**Comment by crazy6995** [comment]
@0x900x90 
    raw wrapper need some arguments "Header"  , i dont know what to type...  
  help me pls.

**Comment by 0x900x90** [comment]
Please, upload your assets file and write file name inside it, which you can't to extract properly. Use zippyshare.com for example.

**Comment by 0x900x90** [comment]
@DerPopo
Tried to export file from assets of version 5.2.1p1. Used raw and dump. Got this 2 files. Raw file is OK, but dump is incomplete. When i try to use plugin, getting png with wrong colors. Is that the same problem?

http://www46.zippyshare.com/v/M4wQKVud/file.html

I can import exported raw file to PVRTexTool as ARGB4444. Result is fine.

**Comment by DerPopo** [comment]
The Texture2D type has changed, the new one will be supported in the next release.

**Comment by 0x900x90** [comment]
In 1.8 version the problem with colors still exists. It's not critical for me. But if you want to fix it, check this function convertToRGBA32 in this class.

https://github.com/vToMy/disunity/blob/master/disunity-core/src/main/java/info/ata4/disunity/extract/Texture2DExtractor.java

**Comment by DerPopo** [comment]
The 16bit texture format problems were caused by different endianess used by Unity between 16 and 24/32bit formats (might be caused by some standards) but now I should have all fixed for the next release.

UABE, in contrast to (most?) other Unity tools, converts the raw texture data so it always has RGBA32 which .tga and .png can handle. Other tools normally use the raw texture data and put them into a matching container format.
