### ISSUE TITLE
Crashes on reading modded asset files.

### ISSUE THREAD

**Issue by echonpie** [DerPopo/UABE#100]
Having a problem with "Golf with your friends" unity game.

Tested both 32bit and 64bit versions.

Your tool used to work fine till a few updates ago where they switched to Unity 5.6 i think. Or at least 5.5.
It still opens the bundles fine, plugins work.. can extract textures and all. But then if I import a new texture in, even if it's one that I just extracted, then the game crashes on start. Even the UABE can't open it anymore, 64bit version crashes immediately, 32bit version hangs for a bit and then opens an empty Asset info window.

Not too bothered, is just golf. Would be nice too have some debugging options maybe.

![gwyf](https://cloud.githubusercontent.com/assets/7239801/22174815/802a9f56-dfe7-11e6-90a9-170b82a22ae0.png)

Edit: UABE version 2.1.

**Comment by DerPopo** [comment]
Found a bug in saving U5.5 .assets files. Could you try if it works with this AssetsTools.dll (64bit)?
[AssetsTools 2.0 U5.5 fix 64bit.zip](https://github.com/DerPopo/UABE/files/722324/AssetsTools.2.0.U5.5.fix.64bit.zip)

**Comment by echonpie** [comment]
Yeah seems to work now. Only did a quick test but it opens modded asset files without a problem now and game loads fine.

Thank you.
