### ISSUE TITLE
Can't open .5.5.0f3 

### ISSUE THREAD

**Issue by Lee91x** [DerPopo/UABE#104]
I am unable to open Assets, with the header ..Bœ..?ô......B°....5.5.0f3' ,

**Comment by DerPopo** [comment]
Are you using the current 2.1b release? If that's the case, could you upload a sample file that doesn't open properly? The current release supports Unity 5.5 .assets files so it's likely a bug if it fails to open.

**Comment by iBotPeaches** [comment]
```
00 00 EC 78 00 0D E3 20 00 00 00 11 00 00 EC 90 00 00 00 00 35 2E 35 2E 30 66 33
```

`5.5.0f3`, previous build of this file was `5.4.1.f1`. Issue opening now on 5.5. Attaching same file for both `5.5.0.f3` and `5.4.1.f1` versions.


[5.5.0f3.zip](https://github.com/DerPopo/UABE/files/741906/5.5.0f3.zip)
[5.4.1.f1.zip](https://github.com/DerPopo/UABE/files/741908/5.4.1.f1.zip)

**Comment by DerPopo** [comment]
I couldn't find an issue with that specific file, likely it's one of the >1100 dependencies.

**Comment by DerPopo** [comment]
Found one issue, does this one work?
[AssetsBundleExtractor_2.1c.zip](https://github.com/DerPopo/UABE/files/747231/AssetsBundleExtractor_2.1c.zip)

**Comment by iBotPeaches** [comment]
That worked :) thanks a ton
