### ISSUE TITLE
[question]making plugin

### ISSUE THREAD

**Issue by CRC32EX** [DerPopo/UABE#117]
## Question
Some .asset file has same file name.
Like this.

```txt
Aassets/chara001/face.png
Aassets/chara002/face.png
Aassets/chara003/face.png
```

Using Plugins and `export to .png` then, file name has indexing.
I do not want to indexing.

I want to exporting .png file, based these values.
make very deep directory and place .png file.
`assets/star/forsassetbundle/startapp/sdchara/00000/u000_template.png`

![image](https://cloud.githubusercontent.com/assets/25629617/24105312/cc101dca-0dc7-11e7-868f-e45ac97ffe23.png)

i tried make custom plugin.
but i couldn't.

please tell me how to get directory string.

sample asset file
[https://www.NoFile.io/f/MzCSiKRsChH](https://www.NoFile.io/f/MzCSiKRsChH)

## Environment
- UABE 2.1c x64
- UABE 2.1c API x64
- VisualStudio 2017 Community (Platform Toolset v141)
- Windows 10 64bit

## Program
```cpp
void ExportAssetBundle(HWND hParentWnd, IPluginInterface *pInterface, IAssetInterface **ppAssets, size_t assetCount)
{
  for (size_t i = 0; i < assetCount; i++)
  {
    IAssetInterface *pAsset = ppAssets[i];
    AssetTypeTemplateField templateBase;
    if (pInterface->MakeTemplateField(pAsset->GetAssetsFile(), 0x8E, &templateBase))
    {
      AssetsFileReader reader;
      LPARAM readerPar;
      unsigned __int64 filePos;
      unsigned __int64 fileSize = pAsset->GetFileReader(reader, readerPar, filePos);
      AssetTypeTemplateField *pTemplateBase = &templateBase;
      AssetTypeInstance instance(1, &pTemplateBase, reader, readerPar, pAsset->GetAssetsFile()->header.endianness, filePos);
      pAsset->FreeFileReader(reader, readerPar);
      AssetTypeValueField *pBase = instance.GetBaseField();

      if (pBase)
      {
        AssetTypeValueField *container = pBase->Get("m_Container");
        AssetTypeValueField *array = container->Get("Array");
        AssetTypeValueField **children = array->GetChildrenList();
        
        printf("child count = %d\n", array->GetValue()->AsArray()->size);

        for (auto j = 0; j < array->GetValue()->AsArray()->size; j++)
        {
          printf("type: %s, name: %s\n", children[j]->GetType(), children[j]->GetName());
        }

        for (auto j = 0; j < array->GetValue()->AsArray()->size; j++)
        {
          AssetTypeValueField *data = children[j]->Get("data");
          auto fileName = data->Get("first");

          // craaaaaaaash!!!
          printf("filename is : %s\n", fileName->GetValue()->AsString());
        }
      }
    }
  }
}

BYTE PluginInfoBuffer[sizeof(PluginInfo)+1*sizeof(PluginAssetOption)];
PluginInfo *GetAssetBundlePluginInfo()
{
  AllocConsole();
  freopen("CON", "r", stdin);
  freopen("CON", "w", stdout);

  PluginInfo *pPluginInfo = (PluginInfo*)PluginInfoBuffer;
  strcpy_s(pPluginInfo->name, "TextAsset");
  pPluginInfo->optionCount = 1;

  pPluginInfo->options[0].action = PluginAction_EXPORT_Batch;
  strcpy_s(pPluginInfo->options[0].desc, "my custom Export to .png");
  pPluginInfo->options[0].unityClassID = 0x8E;
  pPluginInfo->options[0].callback = ExportAssetBundle;

  return pPluginInfo;
}
```

## Console output
```txt
child count = 5
type: pair, name: data
type: pair, name: data
type: pair, name: data
type: pair, name: data
type: pair, name: data
(UABE crash)
```

**Comment by nesrak1** [comment]
I'm not at a computer but from just looking at it I can see a couple of things.
1. I don't remember if this was fixed but I remember from a while ago that the children of an array automatically returned data so you might try removing Get("data")
2. I don't know how c++ handles it but he said the api was made in vs10 before c++ had "auto".

**Comment by CRC32EX** [comment]
@nesrak1 

thank you for reply.

1.  i tried this code, but crashed again.
```cpp
printf("filename is : %s\n", children[j]->GetValue()->AsString());
```

2. yes i saw his `Note.txt` too.
I tested this code.
Compile with Visual Studio 2017 is successfully working.
Plugin is successfully loaded and, successfully export text assets.
[https://mega.nz/#!aVZkVDAC!G7_KC0KrP0d-ZLiroZTuUKQMEHNEtEds3c65i9cq924](https://mega.nz/#!aVZkVDAC!G7_KC0KrP0d-ZLiroZTuUKQMEHNEtEds3c65i9cq924)

**Comment by nesrak1** [comment]
Well since the console output is data, as long as you take out the Get("data") your code looks fine. I can look tomorrow when Im back at my computer.

**Comment by nesrak1** [comment]
`printf("filename is : %s\n", children[j]->Get("first")->GetValue()->AsString());`

**Comment by CRC32EX** [comment]
@nesrak1 
thank you!!!
i can get values!

i try again export .png files each directories.

![image](https://cloud.githubusercontent.com/assets/25629617/24149220/127fd044-0e85-11e7-87ed-722a9669e9bd.png)

**Comment by CRC32EX** [comment]
Thanks for your support, i can successfully export .txt files.

but Texture2D file is can't decode well.

what format is this file?
https://www.NoFile.io/f/QYF90c6ppTr

i want to export .png files.

**Comment by nesrak1** [comment]
Are you using TextureFileFormat?

**Comment by CRC32EX** [comment]
yes.
`pPictureData` is unknown file format.

```cpp
TextureFile *pTexture;
ReadTextureFile(pTexture, pBase2);
printf("texture type is: %d\n", pTexture->m_TextureFormat);

fwrite(pTexture->pPictureData, pTexture->_pictureDataSize, 1, pOutFile);
```

output
```txt
texture type is: 4
```

**Comment by nesrak1** [comment]
![screenshot_20170321-173750](https://cloud.githubusercontent.com/assets/12544505/24174158/3a63a6d0-0e5d-11e7-8189-329c2113c1b5.png)
Does it look similar to this? It's an rgba32 image.

**Comment by CRC32EX** [comment]
yes that is.

when i search "rgb32" then found [similar project](https://github.com/Perfare/UnityStudio/blob/master/Unity%20Studio/Unity%20Classes/Texture2D.cs#L833).
we have to add DDS headers.

thank you, i will try LoadPNG.

**Comment by DerPopo** [comment]
GetTextureData converts the texture to raw RGBA32. Use it after ReadTextureFile and pass a memory buffer with pTexture->m_Width*pTexture->m_Height*4 bytes.

Once you have the RGBA32 data, it can be used to create the .png (using lodepng with a custom function for UTF-16 file names in this sample). The data has to be flipped vertically though.
```	BYTE *flipDataTmp = (BYTE*)malloc(g_TextureWidth * 4);
	if (flipDataTmp == NULL)
		MessageBox(NULL, TEXT("Out of memory!"), TEXT("ERROR"), 16);
	else
	{
		unsigned int stride = g_TextureWidth * 4;
		unsigned int halfHeight = g_TextureHeight/2;
		unsigned int curLinePos = 0;
		unsigned int curEndLinePos = stride*(g_TextureHeight-1);
		for (unsigned int y = 0; y < halfHeight; y++)
		{
			memcpy(flipDataTmp, &textureData[curLinePos], stride);
			memcpy(&textureData[curLinePos], &textureData[curEndLinePos], stride);
			memcpy(&textureData[curEndLinePos], flipDataTmp, stride);

			curLinePos += stride;
			curEndLinePos -= stride;
		}
		free(flipDataTmp);
	}
	lodepng_encode32_fileW(targetFile, textureData, g_TextureWidth, g_TextureHeight);
```

**Comment by CRC32EX** [comment]
@nesrak1 
@DerPopo 

thank you.
implement is completed.
