### ISSUE TITLE
Unable to open asset again after text modification with plugin

### ISSUE THREAD

**Issue by inihility** [DerPopo/UABE#119]
I'm trying to do some localization for a game.

I'm using the plugin "Export to .txt" to export a text field and modify it in Notepad++ and then "Import to .txt" back into the asset file, everything shows up fine when I check the data with "View Data" but after I save the asset file and try to run the game or reopen it with UABE it doesn't work, the game recognizes corrupt data and UABE simply stops responding after a while.

The text is in .xml format as far as I can tell.  I'm not sure if I am doing anything wrong, I read another issue here where there was mention of ensuring the changes match up with the original but that seemed to be targeted at modifying the raw data.

Please advise.

**Comment by ShadySt** [comment]
I have a similar problem, described it in separate thread. 
[https://github.com/DerPopo/UABE/issues/120](https://github.com/DerPopo/UABE/issues/120)

**Comment by inihility** [comment]
> I have a similar problem, described it in separate thread.
> #120 

Are you able to open the asset again after saving to it? UABE freezes for me.

**Comment by inihility** [comment]
Seems to be a similar issue to #109, is there a fix on the way? Can share the .asset file but it's over 1GB...

**Comment by ShadySt** [comment]
I think it's not because same issue goes with any file format like Texture2D, MovieTexture, etc.

**Comment by DerPopo** [comment]
It should now be fixed with 2.1d.

**Comment by inihility** [comment]
Solved in 2.1d, awesome! 💃 

Much appreciation.
