### ISSUE TITLE
Export/Import TextAsset

### ISSUE THREAD

**Issue by Marsi84** [DerPopo/UABE#12]
Hi DerPopo,

I would like to thank you for this freat tool you provided us.

I'm trying to use UABE to translate game contents. 
To do that I open the resource.asset file and look for the textasset type files (as someone said before me a search option or some kind of filtering would be great). 

Once I find them I use the Text Plugin to export them creating a .txt file, I edit the file translating only the strings that need to be translated and save it.

Then when I go back to UBAE to import my file back into the asset bundle it seems it doesn't make any changes. It doesn't replace the file with the one i edited.

Am I doing it the wrong way? Do you have any suggestions?

Thank you in advance for your consideration.

**Comment by DerPopo** [comment]
Does File->Save show a save dialog? If it doesn't, there is a bug in the plugin.

Searching and sorting works right now and will be released with the next version.

**Comment by Marsi84** [comment]
Thank you for the reply DerPopo, I managed to solve the problem! :)

Btw not sure if UABE is supposed to work with any Unity game but I found out that if I try to import files into Planetbase (released yesterday on Steam) UABE crashes (same for UAE actually).

**Comment by DerPopo** [comment]
What kind of data do you import (and do you use asset dumps, raw data or plugins)?
The Texture plugin of the current release can crash with games using Unity 5.2 (maybe also with 5.1).

**Comment by Marsi84** [comment]
I'm only working with textassets for translations. I'm using the plugin to both export and import .txt files

**Comment by DerPopo** [comment]
Does it crash during File->Save or does it while using the plugin?

**Comment by Marsi84** [comment]
During the File-> Save

**Comment by DerPopo** [comment]
Ok, one last thing that might help me to reproduce it : which Unity version does Planetbase use? You can find it in the mainData or any .assets file at the beginning (using a hex editor or even notepad). It should look similar to "5.2.0f3".

**Comment by Marsi84** [comment]
5.0.4f1

**Comment by Marsi84** [comment]
So, one more update, if i do File-> Save and try to overwrite it crashes, if i do File-> Save and create a new file it doesn't crash.

**Comment by DerPopo** [comment]
I forgot to make it check whether the file was successfully opened for writing, which is not possible if it already opened that file for reading.
