### ISSUE TITLE
Unity 5.5.2 support?

### ISSUE THREAD

**Issue by ShadySt** [DerPopo/UABE#120]
Hi, I'm faced a problem using UABE.
I can open and extract any Unity 5.5.2 assets as usual. I can import and save .assets files too.
But when I open my game it crashes. 
I still get error if I don't change file content. 
![error](https://cloud.githubusercontent.com/assets/16884653/24582997/c020f39a-1745-11e7-98a3-5a6c2360c043.png)

Is Unity 5.5.2 fully supported now?
Game log
[output_log.txt](https://github.com/DerPopo/UABE/files/888072/output_log.txt)

Game assets (you need to download both)
[https://drive.google.com/open?id=0B6aBQExfqzJ7ZmlUMnZGeE1HRFU](https://drive.google.com/open?id=0B6aBQExfqzJ7ZmlUMnZGeE1HRFU )

How to see a problem:
1. Open .assets file with UABE
2. Extract any asset (txt file, ogv movie texture etc) with specific plugin.
3. Import asset that you extracted back.
4. Save .assets file and close UABE
5. Open same .assets file again, you will see a problem.

**Comment by 0x900x90** [comment]
There is no usefull information in log file. Upload your 5.5.2 asset file for testing.

**Comment by ShadySt** [comment]
Done. Uploaded both .assets and .resS files.

**Comment by 0x900x90** [comment]
It's huge. I don't know how to test it. Maybe you can describe what manipulations you made with file before placing it into game folder? And let's wait what DerPopo can say about you problem.

**Comment by ShadySt** [comment]
Ok. You can:
1. Open .assets file with UABE
2. Extract any asset (txt file, ogv movie texture etc) with specific plugin.
3. Import asset that you extracted back.
4. Save .assets file and close UABE
5. Open same .assets file again, you will see a problem.

**Comment by 0x900x90** [comment]
You right. Plugin destroys typetree. You can use export/import dump. But i found another problem. Some characters missed in dump.

**Comment by DerPopo** [comment]
Time for a bugfix-fix-fix! Before I release this as 2.1d, could you please check if it fixes the error?
[AssetsBundleExtractor_2.1d_RC.zip](https://github.com/DerPopo/UABE/files/890968/AssetsBundleExtractor_2.1d_RC.zip)
It should fix the escaped line breaks (\n or \r) in dumps and saving the TypeTree. 
I've simply forgotten to swap scriptIndex for classId in the condition whether a type needs two hashes (MonoBehaviour) or one. 

Other changes :
```
Fixed a bug that ResourceManager names are applied to File ID 0's assets if the dependent .assets file that gets the name isn't loaded.
Improved performance of batch dump export.
Fixed the suggested file path name for the XP dialog fallback.
```

**Comment by 0x900x90** [comment]
Tested right now.

Export/reimport using txt plugin - OK.
XP export dialog and suggested file names - OK.
ResourceManager names - OK.

**Comment by DerPopo** [comment]
Thanks for the feedback!
2.1d and 2.1d API are both released now.

**Comment by ShadySt** [comment]
Thanks! I love you! It works!
