### ISSUE TITLE
Can't find "Export sound" option in "Plugins"

### ISSUE THREAD

**Issue by Explorare** [DerPopo/UABE#125]
![image](https://cloud.githubusercontent.com/assets/5090766/25065992/9cc256e8-224c-11e7-9c5e-1e5321d72913.png)

System: Windows 10 15063

I've installed V C++ 2013 but still get the error "Unable to load the PVR tex lib". And I've unlock the 2 dll files.

**Comment by DerPopo** [comment]
Looks like it's unable to load any .dll files manually. What files and folders are beneath AssetBundleExtractor and AssetsTools?

**Comment by Explorare** [comment]
D:\Temp\2017-04-13\tools\AssetsBundleExtractor\
AssetBundleExtractor.exe
AssetsTools.dll
classdata.tpk
ModInstaller.dll

**Comment by Explorare** [comment]
I tried to extract all BGMs in in an app [jp.co.koeitecmo.kakutora.apk](https://www.dropbox.com/s/hvcq8gotxn6kt6z/jp.co.koeitecmo.kakutora.apk?dl=0).
Some of the BGMs can be downloaded from http://assets.kakutora.techarts.co.jp/master-android/ .
What's the proper way to do this? Thanks.

**Comment by DerPopo** [comment]
You need to download the 2.1 release and then move the 2.1d files into the extracted 2.1 folder, overwriting existing ones.

**Comment by Explorare** [comment]
Now the app keep telling me "Unable to open the output file!" when I tried to export the sound. Could you please help me? Thanks.

[individual_bgm_m09@F84B7E7A_uncomp.zip](https://github.com/DerPopo/UABE/files/929625/individual_bgm_m09.F84B7E7A_uncomp.zip)

**Comment by DerPopo** [comment]
Even though I thought I fixed all charset issues, make sure to select a directory without any non-ASCII characters (such as Japanese) and make sure the directory is writable. I couldn't reproduce that issue, even with some non-ASCII characters.

**Comment by Explorare** [comment]
Steps to reproduce the behavior:
1. Download and extract `AssetsBundleExtractor_2.0_64bit.zip` and `AssetsBundleExtractor_2.1d.zip`. It's `D:\Temp\2017-04-13\tools` in my computer. 
2. Download `individual_bgm_m09@F84B7E7A.unity3d` and `individual_bgm_m09.unity3d.manifest` from [game server](http://assets.kakutora.techarts.co.jp/master-android/).
3. Execute `AssetBundleExtractor.exe`. 
File -> Open -> individual_bgm_m09@F84B7E7A.unity3d 
-> "This bundle file is compressed! Do you wish to unpack it?" -> Yes 
-> individual_bgm_m09@F84B7E7A_uncomp.unity3d
-> 
![image](https://cloud.githubusercontent.com/assets/5090766/25161271/8b1d9fc6-24ed-11e7-827d-83f5a0ea4928.png)
-> Info -> Select the AudioClip assets
-> Plugins -> Export sound -> OK
-> D:\Temp\2017-04-13\tools\output.wav
-> Unable to open the output file!

**Comment by DerPopo** [comment]
I couldn't reproduce it, even in a "blank" Win10 VM. Probably the user account doesn't have the file creation and write privilege in the target folder. Try running UABE with admin privilege or extend the access privilege through explorer (right click on folder, settings, security).

**Comment by Explorare** [comment]
Umm... That's weird. I tried the same operation in a clean installed Windows 8.1 VM and met the same error. I've tried using admin mode but not work either. But my friend followed these steps without any problem. I'll tried to check this out. Thanks for your supprot.

**Comment by Explorare** [comment]
I downloaded v2.0 and applied bug fix for 2.1 by mistake. Noob me : (
![image](https://cloud.githubusercontent.com/assets/5090766/25304732/ce8e082c-279f-11e7-8007-9d5cf2388f15.png)
