### ISSUE TITLE
Fail to writing (prefab file)

### ISSUE THREAD

**Issue by jclitwin** [DerPopo/UABE#131]
Yo DerPopo,

Can you help me in something?

[IMG]https://image.prntscr.com/image/00c51d11e4504c2c9dbeedf6b6854d82.png[/IMG]

I have some problem for extract this _skeleton file. I know this prefab file is a .fbx file.

I need to extract all _skeleton. Can you help me in to fix? I want to create this file and get all positions, "bip01" and etc, and make it in unity.

[B]mainData file[/B]: https://mega.nz/#!DwY1zbQT!9sgyUd_4HGSqaphmwwIBE7yL3cgvfoXJxn1RYZntrog

Cheers!

**Comment by DerPopo** [comment]
Closing this for https://github.com/DerPopo/UABE/issues/123 .
