### ISSUE TITLE
Unable to open the streamed data file!

### ISSUE THREAD

**Issue by EricPrince811** [DerPopo/UABE#133]
So i used this program on rust before. BTW thanks a lot trolling has been so much fun with the original sounds. Well now after getting the assets open and seeing the sound. I use the plugin and it comes back with the error stated above the title. I did have to extract the sound.asset from the sound.bundle. But the main issue is does this happen on 7dtd too

**Comment by DerPopo** [comment]
Since I own rust, I'll look into it

**Comment by EricPrince811** [comment]
Thank you very much :D I tested it on the recent 7 Days To Die. And I found
that it worked just fine. Rust on the other hand is as stated before cannot
read data stream

**Comment by DerPopo** [comment]
Should work now. Please open a new issue if you have further questions.

**Comment by Corak667** [comment]
Upping the problem: http://imagizer.imageshack.com/img923/4218/DN3Vbz.png
same issue when tried to convert to wav - audio from movies from game:
Hero-U: Rogue to Redemption
https://cloud.mail.ru/public/3H1b/TJGRUj6J3
