### ISSUE TITLE
Monobehaviour Problem

### ISSUE THREAD

**Issue by niznet** [DerPopo/UABE#134]
I edit MonoBehaviour in asset size 400mb+ make game frozen at loading, how i can fix this?
im using latest version, and some MonoBehaviour that not frozen at loading in some value(int) did not change in game(still same with original value).

Unity Asset Version is 4.7f.

**Comment by DerPopo** [comment]
Closing this issue since UABE 2.2 is out. Feel free to open a new issue in case the issue persists.
