### ISSUE TITLE
Can't read asset bundle files

### ISSUE THREAD

**Issue by santaslilhelper** [DerPopo/UABE#139]
The game I was using your program to view updated from 5.3.x to 5.5.x it seems and broke some things.  I updated to your latest 2.1d files which seemed to fix my unbundling issue, but now the assets file it generates won't get the correct content out, the file table is all screwed up in the tool.  Hoping you can help find a fix for this.

Just a note that you should look at my previous tickets as you had to implement some specific workarounds for how the files were structured and compressed I believe.

Here is a sample of the files I was dealing with: https://drive.google.com/open?id=0B5WUIlsciwhBQmg2NVpha284SEE  It should have a texture in it for an ability icon

Thanks again for your great tool! and let me know if ya need anything else from me.

**Comment by 0x900x90** [comment]
Something wrong happens when you remove typetree.

**Comment by DerPopo** [comment]
Closing this issue since UABE 2.2 is out. Feel free to open a new issue in case the issue persists.
