### ISSUE TITLE
Error! Unable to open the streamed data file! (Rust)

### ISSUE THREAD

**Issue by PoroThePanda** [DerPopo/UABE#141]
Hello DerPopo,
The problem I have come when Im trying to extract audio files from sound.bundle (Game Rust). I tried on laptop too but it gives me error "Unable to open streamed data file!". Will be thankful if u check this I saw u said u have the rust so if u only have a moment for this :).

**Comment by PoroThePanda** [comment]
:duck:

**Comment by DerPopo** [comment]
It'll be fixed in the next version.

**Comment by DerPopo** [comment]
Closing this issue since UABE 2.2 is out. Feel free to open a new issue in case the issue persists.
