### ISSUE TITLE
Problem with UV mapping (sort of fixed thanks to 1.8c)

### ISSUE THREAD

**Issue by David184** [DerPopo/UABE#15]
so i tried to rip character from Block n load and i have a problem where the UV mapping exports wrong and it doesn't export the uv map as it should. i tried to rip something else from different game and it did the same thing as it did with the character. i think this is happening to those models that have bones. this is how Distance's car UV map look like after exporting to OBJ http://i.imgur.com/foy3RKe.png i hope you fix this since i would really like to get characters from block n load and the distance car.

also im really thankful you created this tool. it's really really great and i love it! :D
oh and i forget to mention. sorry for my English. i'm from Czech Republic

**Comment by DerPopo** [comment]
I'm not yet quite sure how to fix that bug but I'll see if I can fix it.

**Comment by joyello** [comment]
I can confirm this!

**Comment by David184** [comment]
Thanks that you're going to look into it! i really appreciate it! :)

**Comment by David184** [comment]
hello. thank you for fixing the problem! it actually kinda fixed the problem expect some models are exporting the UV wrong and they look like this http://i.imgur.com/E2G3ldY.jpg but i'm really thankful that you sort of fixed this bug! :)

**Comment by DerPopo** [comment]
It looks like the UV channels are offset somehow. What happens if you insert the line "vt 0 0" once or twice before the first line starting with "f " (and do that for all submeshes if there are multiple)?

**Comment by David184** [comment]
Where do i put the line? (btw i forget to mention that i have no experience with coding/programming so i apologize if i don't get some stuff)

**Comment by DerPopo** [comment]
You can open the .obj file with strange UVs with notepad. Search for "# Faces" and create a new line before it and type "vt 0 0". If it doesn't look better, insert a second line.
It won't produce a perfect result but if it looks better, it's probably only a simple bug for me to fix.

**Comment by David184** [comment]
Thanks! i tried it and it works! there is only one UV vertex that i got to move but that's not a problem.

**Comment by DerPopo** [comment]
Then it's what I assumed. I will look into fixing it but I'm a bit busy right now.

**Comment by joyello** [comment]
confirming the issue :)
