### ISSUE TITLE
repack bundle file possible wrong

### ISSUE THREAD

**Issue by zxfishhack** [DerPopo/UABE#150]
with UABE edit a bundle file, export the assets file and the import it will increase 3 bytes, below is what changed.

![uabe bug](https://user-images.githubusercontent.com/5556389/29740242-afe4eac4-8a84-11e7-83e3-2a25058ae7ab.png)

**Comment by DerPopo** [comment]
It aligned the .assets file to a four-byte boundary and set the offset accordingly (which is the QWORD value set to 3 in this case).
While that isn't necessary in that case, it should not cause any issues either. As long as Info works on both bundles without generating a garbage asset list, the bundle will be fine.

**Comment by zxfishhack** [comment]
i found only one file doing that will make the game crash. remove the extra byte will work.

**Comment by DerPopo** [comment]
That might be related to the block size (the two "00 35 6F 04" values), which should indeed be updated to reflect the alignment.

**Comment by DerPopo** [comment]
Closing this issue since UABE 2.2 is out. Feel free to open a new issue in case the issue persists.
