### ISSUE TITLE
Queston 

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [DerPopo/UABE#152]
can you make your tool to extract .unity3d files? like the attachment on this question.
[New WinRAR ZIP archive.zip](https://github.com/DerPopo/UABE/files/1271739/New.WinRAR.ZIP.archive.zip)

**Comment by DerPopo** [comment]
I tested it and couldn't find any issues with opening the file.

**Comment by TheRealPiggyWiggy** [comment]
how do i excract the file?
