### ISSUE TITLE
UABE CAB~~ BUG

### ISSUE THREAD

**Issue by takid2848** [DerPopo/UABE#153]
I am extracting 'dynamix' and i was extracting the data files,

maybe that files were too many files (maybe 1970 files)

so I meched all the files

![a](https://user-images.githubusercontent.com/31562186/29994016-d36421dc-9000-11e7-8328-cc201de96021.png)

and this happened

![b](https://user-images.githubusercontent.com/31562186/29994023-f3efbeb6-9000-11e7-9008-a54ede4c5bdd.png)

so i clicked yes, and clicked info, and this happened..

![c](https://user-images.githubusercontent.com/31562186/29994026-1aaa70be-9001-11e7-97ad-6b5fe1cb4652.png)

lol, if you want to test it, 

please use this

[Downloads.zip](https://github.com/DerPopo/UABE/files/1272005/Downloads.zip)

choose all the files, and view it, just one file will be choosed..

I think you can fix this!

Please fix this.... :)

**Comment by DerPopo** [comment]
Only one bundle can be opened at a time. You can use the command line to extract all bundle files as described in Usage.txt.
