### ISSUE TITLE
Batch job? For Multiple items

### ISSUE THREAD

**Issue by ffleader1** [DerPopo/UABE#155]
Hi.
I am trying to replace around 200+ images file in an .asset file with another 200. Granted, they all have the same name, but I have no way to let the program auto-detect and replace the files correspondingly. And of course I can't sit for hours replacing the images by hand. That would cause error.
All in all, I mean...it's nice to have the program the ability to replace files automatically based on their name.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out, which supports batch import. Please reopen this issue or open a new issue if you have further questions.
