### ISSUE TITLE
Ability to dump info to a file from CLI

### ISSUE THREAD

**Issue by rennard** [DerPopo/UABE#158]
Hi, by the way, great tool & thanks for your hard work. I'm trying to do something for my job which requires loading in thousands of .unity3d files, and checking the contents of each bundle, e.g. what shader information is held in each bundle etc. I can see this information easily through the GUI but I need to be able to automate this through CLI. I can't find any way of doing this currently with your software, so I was hoping you could either give me a hint on how to do this or give me a point in the right direction to implement it myself? Thanks a lot

**Comment by jack980517** [comment]
It's not supported right now. See #7

**Comment by DerPopo** [comment]
Closing this for https://github.com/DerPopo/UABE/issues/7 .
