### ISSUE TITLE
[ERROR] Unknown 2D Texture Asset Format!

### ISSUE THREAD

**Issue by Sernikx** [DerPopo/UABE#159]
I was using UABE to extract Gwent: The Witcher Card Game assets (it's a Unity game). Previously it worked, but I believe the game was patched to prevent it and whenever I try to export to PNG, I'm getting the Error mentioned in the description.

The only thing I can do is to export Raw or Dump, but don't really know how or even if it's possible to convert these files to PNG, using some other program?

Or is there nothing I can do and have to wait for possible UABE updates?

**Comment by DerPopo** [comment]
The game probably uses Unity 2017.1, which isn't fully supported in the current UABE version. This will be fixed in UABE 2.2. I've still got to implement a couple of things but I try to get it finished soon.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out. Please open a new issue in case there still are problems.
