### ISSUE TITLE
.Ogg Plugin, (please?)

### ISSUE THREAD

**Issue by Marcusjoshua** [DerPopo/UABE#160]
Im trying to extract a .ogg file, and there is no plugin for it, anyway anyone can make a .ogg file extractor?
[![Screenshot from Gyazo](https://gyazo.com/444968f7ecec415c2f8ee07e1c0c80df/raw)](https://gyazo.com/444968f7ecec415c2f8ee07e1c0c80df)

**Comment by DerPopo** [comment]
You need to move the files from the 2.1d folder to 2.1.
