### ISSUE TITLE
Export Raw Asset from Assets in API(same function as "Export Raw" button)

### ISSUE THREAD

**Issue by dmc31a42** [DerPopo/UABE#163]
Hello, I'm translate(localization) mod maker. 
i've seen and tried #58, #43,  https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor&p=457416&viewfull=1#post457416 and https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor/page8&p=459961#post459961 
These are useful for me.
but, i cannot find a way to export raw asset file from *.assets in API.
I'm pleasure to let me know how to that.
Or, just do extract from existing "*.assets" file from offset "AssetFileInfoEx->absolutePos" until size "AssetFileInfoEx->curFileSize", that's it?
thanks

**Comment by DerPopo** [comment]
Sorry for the late response.
As you suspected, you simply need to copy AssetFileInfoEx->curFileSize bytes from the .assets file from the file offset AssetFileInfoEx->absolutePos .

**Comment by DerPopo** [comment]
Closing this issue. Please reopen this issue or create a new one if you have further questions.
