### ISSUE TITLE
fileEngineVersion limit too short

### ISSUE THREAD

**Issue by nesrak1** [DerPopo/UABE#165]
When the fileEngineVersion is longer than 19 characters, it gets chopped off and errors when trying to decompress.
![compatwindow_2017-11-23_23-29-19](https://user-images.githubusercontent.com/12544505/33196655-251c16ac-d0a6-11e7-96d5-5224144fe625.png)
Editing the original file to make it short enough decompresses fine.

**Comment by DerPopo** [comment]
Will be fixed in 2.2.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out. Please open a new issue if this issue persists.
