### ISSUE TITLE
Failed to import dumped TextAsset

### ISSUE THREAD

**Issue by berryboy2012** [DerPopo/UABE#166]
it seems that string variables defined in bumped files cannot have a length higher than 232. A dumped file which can be used to reproduce the problem is attached.
I am using ver. 2.1d, the game version probably be 5.3.4.47953
PS: sorry about my poor English.
[MasterScenario_TextAsset_0_17935969608413859124.txt](https://github.com/DerPopo/UABE/files/1524020/MasterScenario_TextAsset_0_17935969608413859124.txt)

**Comment by DerPopo** [comment]
Will be fixed in 2.2.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out. Please open a new issue if this issue persists.
