### ISSUE TITLE
unable to read the bundle file (invalid file or unknow version)

### ISSUE THREAD

**Issue by yuki2333** [DerPopo/UABE#169]
This tool can be used before a update Now how should I open it
Delete .txt
[scripts.txt](https://github.com/DerPopo/UABE/files/1561732/scripts.txt)

**Comment by DerPopo** [comment]
That file is encrypted or compressed. Only the game code (somewhere in Assembly-CSharp.dll probably) knows what happened to it.

**Comment by flying-neko** [comment]
It's  from azurlane :dog: :u7a7a:

**Comment by DerPopo** [comment]
I might help if you send me an updated Assembly-CSharp.dll from assets/bin/Data/Managed since the version on that game's website does not yet have encrypted bundles. If you use dnSpy, you can take a look at ResourceMgr.loadAssetBundleSync.

**Comment by yuki2333** [comment]
Thanks for your help.
[Assembly-CSharp.dll.txt](https://github.com/DerPopo/UABE/files/1564899/Assembly-CSharp.dll.txt)

**Comment by yuki2333** [comment]
Thank you . The problem has been solved.

**Comment by DerPopo** [comment]
In case anyone else has this problem, take a look at CriFsLoadAssetBundleRequest.Update, which should receive the uncompressed/decrypted data.

**Comment by ComputerFix** [comment]
Assets Bundle Extractor Unable not be read! Invalid or unknown file 100%

https://www.youtube.com/watch?v=sXq54Ovw1GE&feature=youtu.be&ab_channel=Xpirate04

**Comment by CandymanScripts** [comment]
> Assets Bundle Extractor Unable not be read! Invalid or unknown file 100%
> 
> https://www.youtube.com/watch?v=sXq54Ovw1GE&feature=youtu.be&ab_channel=Xpirate04

video deleted

**Comment by iWalk809** [comment]
> > Assets Bundle Extractor Unable not be read! Invalid or unknown file 100%
> > https://www.youtube.com/watch?v=sXq54Ovw1GE&feature=youtu.be&ab_channel=Xpirate04
> 
> video deleted

WHO IS DELETING IT BRUH

**Comment by toastchest** [comment]
what is CriFsLoadAssetBundleRequest.Update???

**Comment by toastchest** [comment]
what is:CriFsLoadAssetBundleRequest.Update???

**Comment by parasager** [comment]
a
