### ISSUE TITLE
Not working 100% on some Unity 5 files

### ISSUE THREAD

**Issue by PlanK69** [DerPopo/UABE#17]
Hi there.

This prog is great, but it doesn't work 100% on Unity 5 files, for example on files from Hearthstone.

Here is the files that I'm referring to, for your reference: https://www.dropbox.com/s/wsd3u4pb3xl4roc/spellsjaJP0.unity3d?dl=0 and https://www.dropbox.com/s/rdivj7rd6pzi7wq/soundsjaJP0.unity3d?dl=0 .

I don't know ALOT about this stuff, but I'm guessing that the files haven't been mapped yet, and that's why most (about 70%) of the files that are shown by the UABE shows as "unknown asset".

I know that the 2 files contain .ogg audio files, and your UABE tool can only extract about 30% of them currently.

It would be awesome if the tool could be updated to allow for 100% extraction of these 2 files.

Your work is appreciated!

**Comment by DerPopo** [comment]
Only the assets with the type AudioClip contain audio data, the others (like AudioSource, GameObject or MonoBehaviour) don't. I couldn't find any problems with the AudioClips.
