### ISSUE TITLE
.assets dependencies

### ISSUE THREAD

**Issue by Romsstar** [DerPopo/UABE#173]
Suggestion:
If an *.assets file has dependencies, make UABE auto-load the dependencies.
if a *.resS file exists to that .asset file make it auto-load as well.

I don't know if that is supposed to work already, because the 2.2 beta release made it sound like it should, but it doesn't seem to work, as when I try to export, the corresponding dependency is not auto-loaded.

To be clear: Getting the Stream Data not loaded/found issue when an export should actually work.

**Comment by DerPopo** [comment]
It opens the streamed data files (i.e. .resource or .resS) whenever an asset refers to them.
I've made some changes to how .assets files are loaded, so it's certainly possible that there are new bugs. In that case, 2.2 beta 1 *might* work in your case.
I'll see if I can fix it. Is it an .assets file in a normal <Game>_Data directory or is it located inside a bundle? If possible, could you send me an asset dump of the Texture2D or AudioClip you tried to export?
