### ISSUE TITLE
Mod Maker issue

### ISSUE THREAD

**Issue by pro1225** [DerPopo/UABE#174]
First of all, thanks for creating this tool and this helped me a lot for creating a translation patch for unity5 games.

Issues I found for Mod Maker - standalone exe creator. 

1. No matter which path I choose during creation, it seems to save the absolute path to my local computer and users are not able to modify it when they execute the exe, which makes the installer not usable.
2. after installation completes, the exe does not terminates. It's hanging in windows task list.

**Comment by DerPopo** [comment]
1. Relative file paths work fine on my end. If you've selected a path in the same volume as the game files, it should show some path starting with ".\" or "..\" in the changes list. If that does not work, it's likely a bug. Does your file path contain any special characters or is very long (i.e. > 240 characters)? Also try typing in the file name manually.

2. I am aware of this bug and will try to fix it. It's a racing condition between two threads, where one thread sometimes waits forever for the other to close.

**Comment by DerPopo** [comment]
The second issue should now be fixed, though I still couldn't find anything about the first one.

Feel free to report back if you still run across these problems.
