### ISSUE TITLE
Regex filters

### ISSUE THREAD

**Issue by FINDarkside** [DerPopo/UABE#18]
Regex filter for name and a filter for type would help very much when you are looking for something specific.

**Comment by DerPopo** [comment]
The only supported thing except normal name comparison are asterisks (*) to allow any sequence of characters. I don't think it's necessary to add regex support (with a third-party library) for the search except maybe in some very special cases (which I haven't seen yet).

I'll definitely look into adding a type filter though.

**Comment by FINDarkside** [comment]
So there is a search already? I must have missed it. Great program btw.
