### ISSUE TITLE
Texture2D Incorrectly Exported for Certain Assets

### ISSUE THREAD

**Issue by dastrdly6585** [DerPopo/UABE#190]
Using UABE v2.2 (beta 1 & 2); Windows 10

One compressed asset bundle out of a set of compressed asset bundles is now incorrectly exporting Texture2D assets to PNG and TGA files.  Several other compressed asset bundles that are part of the same game export their Texture2D assets correctly.  Furthermore, UABE correctly interprets other types of assets such as MonoBehavior in the problematic asset bundle.  

Edit: UABE interprets the problematic Texture2D files as DXT5Crunched with mip maps (mip map bias of 0).  In contrast, the other asset bundles where Texture2D files can be properly exported have UABE interpreting the Texture2D assets as DXT1 format without mip maps.

This issue only started occurring once new versions of asset bundles came out with an update to the game.  Previously correctly extracted assets before the update are included to show the correct appearance of the textures:

![dice01_broken](https://user-images.githubusercontent.com/13990010/36239188-9f4ba9c2-11d5-11e8-86d3-af0b1eb181e6.png)
![dice01_correct](https://user-images.githubusercontent.com/13990010/36239191-9f8029cc-11d5-11e8-9293-6b080ec73f2e.png)
![dice02_broken](https://user-images.githubusercontent.com/13990010/36239190-9f7259a0-11d5-11e8-86af-5210b209f6e7.png)
![dice02_correct](https://user-images.githubusercontent.com/13990010/36239189-9f639a8c-11d5-11e8-8b94-bcac2bb53133.png)

**Comment by DerPopo** [comment]
Unity has its own crunch fork first used in 2017.3 that doesn't produce data compatible to the original version (not sure if that's intentional). At least that library is much faster than the original and is better at utilizing multiple threads.
Since I can't just link both versions of crunch into the same binary due to naming conflicts, I'll probably include the new version in TexToolWrap.

**Comment by DerPopo** [comment]
The new crunched texture formats are now supported. Feel free to report back if you find further issues.
