### ISSUE TITLE
Is this an open source project?

### ISSUE THREAD

**Issue by ritmoHung** [DerPopo/UABE#192]
I'd like to know whether this is an open source project or not. The problem is that I wanted to make it able to do batch processing, but can't find the source code(I've also checked the 7 days to die website). And which language is used to write this program?

**Comment by mihailogazda** [comment]
I guess not, shame, I could improve some things too...

**Comment by fireundubh** [comment]
The developer said in 2015 he has no plans to open source it. He's probably using proprietary code, thinks Unity will change their formats to defeat his extractor, or he just wants to horde the source so he can take all the credit. It's incredibly annoying, in any case.
