### ISSUE TITLE
Unable to retrieve the script type database!

### ISSUE THREAD

**Issue by oobol2000oo** [DerPopo/UABE#194]
I use this tool to edit [asset file](https://1drv.ms/u/s!AnAKocoSOJ0ViJYkUjSITHJ2XV7qEw) in PvZ Heroes game but when I load the [dll](https://1drv.ms/u/s!AnAKocoSOJ0ViJ0H0UoOaVO6l4a7qw) (I dump it from IL2CPP) it show the error
![image](https://user-images.githubusercontent.com/8504326/37096544-865eefba-224b-11e8-8129-0f8f0934e7cd.png)

Version use: 2.2

**Comment by monkeysaboteur** [comment]
I have the same problem.

**Comment by DerPopo** [comment]
The file does seem to have an error, however it should now be possible to view all valid MonoBehaviour types. Feel free to report back if there are further issues.
