### ISSUE TITLE
No file opened

### ISSUE THREAD

**Issue by creampuffs13** [DerPopo/UABE#2]
I dont know what I'm doing wrong but even tho I already opened a .assets file it still says no file opened. :/

**Comment by DerPopo** [comment]
"No file opened." will only disappear for bundle files.
It should open a new window for .assets files. If it doesn't, could you tell me your OS and what exactly you tried to open the .assets file?

**Comment by creampuffs13** [comment]
This happened
![dsdsds](https://cloud.githubusercontent.com/assets/7610310/9816483/e41d9306-58cf-11e5-9b86-bafeefffbeb4.jpg)

when I tried opening this file
![lalalalala](https://cloud.githubusercontent.com/assets/7610310/9816540/29b8090a-58d0-11e5-8902-59dd285af567.jpg)

**Comment by creampuffs13** [comment]
This happened when
![dsdsds](https://cloud.githubusercontent.com/assets/7610310/9816590/8b551a54-58d0-11e5-9dca-b176140c9a90.jpg)

I tried to open this file or am I doing it wrong?

![lalalalala](https://cloud.githubusercontent.com/assets/7610310/9816589/8b54d990-58d0-11e5-9d23-1c047b690486.jpg)

**Comment by creampuffs13** [comment]
This is what happened
![dsdsds](https://cloud.githubusercontent.com/assets/7610310/9816631/cf503be4-58d0-11e5-852a-a35f29d2e2f0.jpg)

When I tried opening this file or am I doing it wrong?
![lalalalala](https://cloud.githubusercontent.com/assets/7610310/9816632/cf644ab2-58d0-11e5-907d-5d471223c469.jpg)

**Comment by DerPopo** [comment]
There's nothing wrong there. The "No file opened." text is just for bundle files and the new window created is for .assets files.

**Comment by creampuffs13** [comment]
Ah... Sorry I thought it can also extract .assets files >_<

**Comment by DerPopo** [comment]
That's what the buttons on the right are for.
