### ISSUE TITLE
LZ4 compressed bundles

### ISSUE THREAD

**Issue by DerPopo** [DerPopo/UABE#20]
Unity 5.3 (to be released on 8 December) will be able to generate LZ4 compressed bundle files, currently only LZMA bundles are supported by UABE.

**Comment by putyavka** [comment]
Is it possible to implement batched extraction? I have  more than 600 files and extract them manually for analysis is too long.
Can you publish source code of this tool?

**Comment by Devilin-Pixy** [comment]
I can confirm that Unity 5.2.2 (f1) extracts fine, while Unity 5.3.0 (f0) seems to have issues with them now. Hoping there will be a fix for the LZ4 compressed bundle files.

Love your tool, keep up the good work

**Comment by DerPopo** [comment]
They changed a lot in the bundle file format (not only for LZ4 bundles). I'll reverse-engineer a bit because some fields aren't always the same in all bundle files I tested.

**Comment by DerPopo** [comment]
I found the part in the player that reads the file headers and already got some useful info out of it.

**Comment by Devilin-Pixy** [comment]
Sounds good :-)

**Comment by DerPopo** [comment]
5.3 bundles work so far. I will create a type database for 5.3.1p3 and then the update should be ready.

**Comment by DerPopo** [comment]
1.8.1 is released. If there are any problems with Unity 5.3 bundles, please open a new issue.
