### ISSUE TITLE
Installers do not exit properly after completion

### ISSUE THREAD

**Issue by Tahvohck** [DerPopo/UABE#202]
This is most noticeable when making many small modifications over the course of a project, all that compile to the same EXE. Once run, the program acts like it's exited and closes the window but the task stays running in the background as a zombie. I have to go into task manager and kill it.

Windows 10 Version 1709
Build 16299.371

**Comment by DerPopo** [comment]
The racing condition that caused this issue should now be gone. Feel free to respond if this bug has not been resolved properly.
