### ISSUE TITLE
Support for unity 2018

### ISSUE THREAD

**Issue by thejeffreyallen** [DerPopo/UABE#210]
Just wondering if there is a plan to add support for unity 2018. Not sure if you're still developing this program.

**Comment by DerPopo** [comment]
I am working on the next release, though there still are some issues with crunched texture support I have to fix first.
In the meantime, you can use this updated classdata file (though not all plugins of beta2 support Unity 2018) : [classdata 2018.1.1f1.zip](https://github.com/DerPopo/UABE/files/2095268/classdata.2018.1.1f1.zip)

**Comment by DerPopo** [comment]
The new 2.2 beta3 release supports Unity 2018.1.
