### ISSUE TITLE
error popup interrupts batch export

### ISSUE THREAD

**Issue by iwanPlays** [DerPopo/UABE#211]
Thank you for making Unity modding possible and awesome!

If I export 800 meshes and 50 of them have errors (something about 3 values in War Robots (free2play on Steam)), I will get one message per mesh.

Ideally, there would be one collective error message at the end or a log view tracking errors while exporting. Or a logfile and one error at the end telling to look in that file.

**Comment by DerPopo** [comment]
Will be fixed, I missed writing some of the error messages into the log for batch export instead of separate message boxes.

**Comment by DerPopo** [comment]
Should be fixed now, feel free report back in case there are further issues.
