### ISSUE TITLE
Dumping Serialized Data

### ISSUE THREAD

**Issue by nfearnley** [DerPopo/UABE#213]
I'm trying to dump serialized data from a MonoBehaviour. This object contains references to other objects which is stored in the serialized asset file as PPTr's. When I dump them, they look like this:

```
{
    "0 MonoBehaviour Base":
    {
        "0 PPtr<GameObject> m_GameObject": 
        {
            "0 int m_FileID": 0,
            "0 SInt64 m_PathID": 0
        },
        "1 UInt8 m_Enabled": 1,
        "0 PPtr<MonoScript> m_Script": 
        {
            "0 int m_FileID": 1,
            "0 SInt64 m_PathID": 1092
        },
        "1 string m_Name": "Thingy",
        "0 Array m_values": [
            {"0 PPtr<$Module> data": 
            {
                "0 int m_FileID": 2,
                "0 SInt64 m_PathID": 4
            }},
            {"0 PPtr<$Module> data": 
            {
                "0 int m_FileID": 3,
                "0 SInt64 m_PathID": 4
            }},
            {"0 PPtr<$Module> data": 
            {
                "0 int m_FileID": 4,
                "0 SInt64 m_PathID": 4
            }},
            ...
        ],
        "0 PPtr<$Sprite> m_iconOne": 
        {
            "0 int m_FileID": 93,
            "0 SInt64 m_PathID": 1
        },
        "0 PPtr<$Sprite> m_iconTwo": 
        {
            "0 int m_FileID": 94,
            "0 SInt64 m_PathID": 1
        },
        ...
    }
}
```

Unfortunately, it doesn't seem to also dump the fileId map for that asset file, so I can't tell which files those FileID indexes are supposed to point to.

If I use then "View Data" button, I'm able to follow these PPtr references.

I would like to see at least one of the two following features:

1. Ideally, be able to dump a whole tree of data, properly following PPtr references. I realize this may run into issues, like cyclical references.
or
2. Be able to export a map of FileIDs to Asset File GUIDs for a particular asset file.

**Comment by DerPopo** [comment]
I've added the second option to the View->Dependencies dialog.

**Comment by nfearnley** [comment]
Thanks for the quick update! I've tried it out and it seems to do the job.

**Comment by DerPopo** [comment]
Feel free to report back if you find any inconsistencies in the exported files, or have further questions.
