### ISSUE TITLE
[request] Compressed mesh and texture support

### ISSUE THREAD

**Issue by Acewell** [DerPopo/UABE#22]
Hi, i tried to sign up at the 7daystodie forum but you must have an account in that game and not just the forum in order to post or communicate there, so here i am. :)

I use this tool more than most other unity tools and this one has the potential to be the best around. 
I just wanted to request support for compressed mesh and textures.
I am seeing a lot of these in different games and adding support for them would be a step closer to perfection! Thanks :)

**Comment by DerPopo** [comment]
Compressed meshes most likely won't make it to the next release but I'm working on the compressed texture formats.

**Comment by DerPopo** [comment]
It will support all texture formats (as of 5.3.2p3) with the next release except ATC_RGB4, ATC_RGBA8 and YUV2 (the latter one will be there but with color channel problems).

**Comment by santaslilhelper** [comment]
@DerPopo are compressed meshes still on the todo list or any way for me to do it myself in any round about ways?

Thanks for any advice

**Comment by ChioriGreene** [comment]
I would also like to know what is the suggested work around is for this? I can't seem to find any other util that will convert compressed meshes to obj, so some update or insight would be appreciated.

**Comment by DerPopo** [comment]
It's still on my todo list but it could take a while (2-3 months) until I can look into it as I'm quite busy at the moment.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out. Feel free to open a new issue if there are any problems with compressed meshes since I haven't had the chance to test it on many meshes.
