### ISSUE TITLE
Drag Assets info to stop the computer.

### ISSUE THREAD

**Issue by ji64922** [DerPopo/UABE#221]
I drag assets info list, computer is stop and beep sound is play.
error video:
https://youtu.be/8dc1RS7JAZ4

**Comment by DerPopo** [comment]
That looks like some kind of window event overflow (also considering the sudden RAM usage), but UABE does nothing special during the selection except updating the right half of the window once, and that issue does not appear on my end. I haven't tested it on Win10 though, I'll try that tomorrow.

Are you using any programs that could 'mess' with other windows, such as typing assistants? Are any gamepads or similar devices attached?

**Comment by ji64922** [comment]
@DerPopo
No I use USB mouse, keyboard, speeker and  LAN card
