### ISSUE TITLE
Rigging flipped on exported SkinnedMesh

### ISSUE THREAD

**Issue by KekMcGee** [DerPopo/UABE#222]
Really excited to see that exporting rigged models is finally supported, AssetStudio is already great for this, however sometimes it rips models in the first frame of their animations. but I've found an issue as stated in the title.

Samples if needed: https://mega.nz/#!88gSzaBC!_8PacxBhglDKPpD1rYyhCpE7gxJPabfaJylN_JuAqow

Example of the issue: https://cdn.discordapp.com/attachments/303717803620302848/475447809932394507/unknown.png

**Comment by DerPopo** [comment]
I'll close this issue since the fix is released. In case this issue persists, feel free to reopen this issue or open a new one.
