### ISSUE TITLE
Is there a way to apply a .emip file to .assets without using GUI?

### ISSUE THREAD

**Issue by enumag** [DerPopo/UABE#225]
To make Unity assets editing easier, we have a little script that can generate an .emip file. Then we just open UABE and apply this file to the desired .assets file.

It works far better than editing everything manually with UABE GUI but we still have quite a few assets files to manage so if we could apply the .emip file to .assets file using some a command line tool, it would be quite helpful because then we could automatize it completely. Or if there is some DLL function or other API like that which we could use in our own program, that would work too.

If there is no way to do this currently, nor you have any plans to add anything like that, then just close this issue. Thanks for answering.

**Comment by enumag** [comment]
ping @DerPopo

**Comment by DerPopo** [comment]
Sorry for the late response.

I've added a console option to apply an emip file. I did not test it thoroughly, so feel free to report problems with it.
Just run ```AssetBundleExtractor applyemip <.emip file> <base directory>```
[AssetsBundleExtractor_2.2beta4_applyemip.zip](https://github.com/DerPopo/UABE/files/2408196/AssetsBundleExtractor_2.2beta4_applyemip.zip)

**Comment by DerPopo** [comment]
It works fine on my end with 2.2 beta 4. The function mentioned in the error message exists in beta 4.

The base directory is for relative file paths in the emip file. If you have absolute file paths in the emip file, you can choose any directory (```.``` could also work). The command renames the original files to *.bak0000 (or 0001,...) just like mod installers.

**Comment by enumag** [comment]
I must have had an older version of UABE, sorry. Everything seems to work alright now, I'll let you know if I run into something new.

Thank you very much for this feature!
