### ISSUE TITLE
Example batch file for exporting/importing .asset files

### ISSUE THREAD

**Issue by Akintos** [DerPopo/UABE#226]
Can you provide an example file for the new feature?

When I tried exporting a resources.assets file, the output was
```
Batch extract : 1 bundle files to process found.
Batch extract : Extracting from bundle file 1/1 (C:\Games\PC Building Simulator\PCBS_Data\resources.assets).
AssetBundleFile.Read : Unknown file version!
Batch extract : The file is invalid or I am too old to read this file format!
Batch extract : unsupported bundle file version!
Batch extract : Done!
```

**Comment by DerPopo** [comment]
The command line option isn't new and allows exporting the .assets files out of bundle (often .unity3d) files and is not suitable if you want to export data from .assets files. 

The UI is what you're looking for if you want to work with .assets files. If you select multiple assets (entries inside an .assets file) of the same type, you can export/import all selected entries with the supported methods (raw/dump/plugin options).

**Comment by Akintos** [comment]
Then is it not possible to automate export/import asset files? (not using GUI)

**Comment by Akintos** [comment]
Thank you for quick answer.

It would be great to have command line option for asset files because I am working on a mod for actively updating game and making new patch manually is quite time consuming.
