### ISSUE TITLE
Additional Texture2D formats (34 - ETC_RGB4, 47 - ETC2_RGBA8, 64 - ETC_RGB4Crunched)

### ISSUE THREAD

**Issue by alex-dommasch** [DerPopo/UABE#227]
Thanks for creating a really cool tool.  It's fun to deconstruct an app and see what's inside.  I was wondering if you had any plans to support additional Texture2D formats, like:  34 - ETC_RGB4, 47 - ETC2_RGBA8, 64 - ETC_RGB4Crunched.  It would be nice to be able to export them as PNG.  Thanks!

**Comment by DerPopo** [comment]
These formats actually are meant to be supported. Do you have a sample file with textures that UABE doesn't want to export?

**Comment by alex-dommasch** [comment]
I'm now guessing it's related to the warning (that I foolishly ignored) at start-up, regarding having to install vc-redist 2013.  I wasn't able to get that installed (I'm running this on an old version of Wine on an old version of Ubuntu, and I can't upgrade right now), so I suppose I'm out of luck on those texture formats until I have time to put a bit more effort into this.  But I *was* able to get many other textures out.  (And I also really appreciate the effort you have put into this tool.)  I'll close this issue now, as it appears the tool is working as designed.

**Comment by DerPopo** [comment]
You could try the msvcp120 and msvcr120 dlls from the [vc13_*_x86 or x64 archive](https://github.com/eladkarako/vc-archive/tree/e7c947df37b111ff912b7826245fbb85710bac51/archives) (should be safe, the Microsoft certificates are valid), in case it's just the redist installer that doesn't work.

**Comment by alex-dommasch** [comment]
Brilliant!  That worked perfectly, thank you.
