### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Straighten-Your-Back** [DerPopo/UABE#240]
I got here from a google search. I want to edit .asset files.

But this project is just three different readmes. There's nothing else in it.

Did OP abandon it and spitefully delete the actual editor? Where's the editor?

**Comment by enumag** [comment]
It's not abandoned, it just isn't open-source. You can download it from [releases](https://github.com/DerPopo/UABE/releases).

**Comment by jack980517** [comment]
Apparantly you didn't bother to check the contents of the readme files, the forum thread the readme links to, the commit history, or the releases section...
