### ISSUE TITLE
Cannot Export Meshes anymore since beta3 from Unity 2017.4.4f1

### ISSUE THREAD

**Issue by StolleJay** [DerPopo/UABE#243]
With beta2 i was able to Export Meshes from Unity 2017.4.4f1 but now since beta3(4) it gives me an "_Unable to read the Mesh asset (Unknown asset format)_".
Also Exporting from Unity 2018.2.10f1 gives me an "_Unable to read the Mesh asset (Unknown asset format)_"

Please fix it then it is a really really helpful Tool.

**Comment by DerPopo** [comment]
As it turns out, it was a simple check that used an uninitialized value. The check did not fail in Debug mode, hence I didn't notice.

**Comment by StolleJay** [comment]
Ok. Good to hear about that and Thanks for the Answer ;)
Hope you can fix that.

**Comment by StolleJay** [comment]
Do you know when you can Release a new Version?

**Comment by DerPopo** [comment]
Should be fixed in 2.2 stable. Feel free to open a new issue if necessary!
