### ISSUE TITLE
Import and Export TextAsset

### ISSUE THREAD

**Issue by thuy321** [DerPopo/UABE#245]
Hi 

First thanks for the program works very well, second I am trying to translate a game in unity but I have a problem.

I extract the TextAsset from GlobalManagement and I manage to modify them and import them back but there are no results, no change is shown when the game starts.

Any ideas on how to solve this? Is there something I still have to do?

I know that this issue already exists but does not show any solution to the problem, sorry if this is repetitive

Thanks and sorry for my bad English

**Comment by DerPopo** [comment]
Did you replace the original file by the modified one after editing? Can you see the changes inside UABE (i.e. open the file after replacing it and then export the asset)?

Another (unlikely) option is that the game might have a copy of the translation data somewhere else, making the one you edited redundant.

**Comment by NicolasHawrysh** [comment]
This would be super useful.

**Comment by xp4xbox** [comment]
The only way I edited text was from he editing the asset.

**Comment by thuy321** [comment]
Hi 
I replaced the textasset by means of the import / export txt plugin, changed the lines I wanted and re-imported it and saved it but when I ran the game it did not change anything, in fact I reopened the file with UABE and confirmed that the textasset had the change he had made but it is not reflected in the game.

I already checked all the textasstes and changed all the ones that had that dialog but still it does not change in the game.

Any idea of why or how to solve it?

Is there any other files or data types that may contain dialogues in addition to textassets?

Thanks

**Comment by thuy321** [comment]
> 
> 
> The only way I edited text was from hex editing the asset.

Hi xp4xbox Have you been able to edit the textassets of a game successfully?

**Comment by xp4xbox** [comment]
@thuy321 what i would do is I would open the asset that has the text, for example `resource.assets` with a program called DNSpy which is my decompiler but has a built-in hex editor. Then I would search for the string I would like to replace, and I simply changed it using DNspy.

**Comment by DerPopo** [comment]
Closing this. Feel free to open new issues if required!
