### ISSUE TITLE
Problem with saving type database file

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#247]
Trying to change unity target version in type database. I opened dat file and just pressed OK. Then deleted all targets and added my string `"5.4.*f*"`. Pressed OK and UABE crashed. x86 version.

And a question about type databases. If i'll add 5.4.5f1 type data base will UABE use my database instead of built-in 5.4.0f3?

Edit: I set target unity version using hex editor. When i loaded 5.4.0 asset file, UABE loaded 5.4.0f3 type database. When i loaded 5.4.5 asset file, it used 5.4.5 database. So, now i only need to be able to set unity target versions for type databases in UABE, not in hex-editor.

**Comment by DerPopo** [comment]
UABE chooses the first database with a matching version string it finds, so it depends on the order in the type package.
The version bug should be fixed in 2.2 stable. Feel free to open a new issue if necessary.
