### ISSUE TITLE
Information about errors while multiexport.

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#249]
When i try to export multiple assets, i can see errors in export window. But this window closes at the end of the export and errors information is not available. Can you add close button for this window or make errors text available somehow? Also error information is not very helpfull. Please, add asset id into error information.

Thanks.

**Comment by DerPopo** [comment]
Progress dialogs now don't close automatically if an error occured and error information now contains the asset IDs.
Closing this, feel free to open a new issue if required.
