### ISSUE TITLE
export texture in RGB565 | wrong color

### ISSUE THREAD

**Issue by wortek** [DerPopo/UABE#25]
Hello, first of all your tool is my lifesaver.
I can export almost all of the textures from my assets, however some Texture2D objects get exported with wrong color because they are in RGB565 format for some reason. If I try to edit and change to RGBA32 the software just crashes.
Can anything be done to export it as png or tga, I need it so badly.

**Comment by wortek** [comment]
Nevermind I managerd

**Comment by DerPopo** [comment]
There indeed is a bug that makes the program crash when changing the texture format but I already fixed it for the next release.

There also was an endianness problem with RGBA4444, so RGB565 might also be wrong. I'll look into fixing that.

**Comment by DerPopo** [comment]
Now (with the next release) all 16bit formats should export and import properly.
