### ISSUE TITLE
Support for unity 2018.3.0f2

### ISSUE THREAD

**Issue by thejeffreyallen** [DerPopo/UABE#250]
I was just curious if this program was still being updated or not. I am currently modding a new unity game, Skater XL. I can do certain things, but it really doesn't like when I try to export meshcolliders and mesh renderers. Any news would be greatly appreciated. Thanks for all your hard work on this program.

**Comment by DerPopo** [comment]
2.2 stable is out now with 2018.3 support. I haven't found anything more on the streamed Meshes, please report back if you have any Mesh assets that UABE can't export properly.

**Comment by thejeffreyallen** [comment]
Thank you so much for replying and the new release. I'll let you know if there's any issues.
