### ISSUE TITLE
Image Editing Broke In Latest Release

### ISSUE THREAD

**Issue by BowDown097** [DerPopo/UABE#256]
So, it seems the latest release has broken image importing. When I use the "Edit" plugin and open the png and all that good stuff and import it using default settings, the image becomes "corrupted" in a sense, to where the game does not read it and it looks a _bit weird._ (Note that they are modified from the original version, both were originally 4096x4096 and transparent but due to GitHub's upload restrictions I had to change size from 2048x2048 and make not transparent)
First image is image I threw into UABE to import, second image is the corrupted one UABE imported. First segment of code is dump of the image before import and I couldn't post a segment of the dump after as it was way too large, but 3rd image attached shows preview in UABE.
![sactx_4096x4096_uncompressed_ui_680dde1c-resources](https://user-images.githubusercontent.com/42720004/50463349-0f413780-0940-11e9-96c4-e5e57dbbc0d2.png)
![sactx_4096x4096_uncompressed_ui_680dde1c-resources assets new-464](https://user-images.githubusercontent.com/42720004/50463360-22ec9e00-0940-11e9-9341-6bebb03713b1.png)
`0 Texture2D Base
 1 string m_Name = "sactx-4096x4096-Uncompressed-Ui-680dde1c"

 0 int m_ForcedFallbackFormat = 4

 1 bool m_DownscaleFallback = false

 0 int m_Width = 4096

 0 int m_Height = 4096

 0 int m_CompleteImageSize = 89478484

 0 int m_TextureFormat = 4

 0 int m_MipCount = 13

 0 bool m_IsReadable = false

 1 bool m_StreamingMipmaps = false

 1 int m_StreamingMipmapsPriority = 0

 0 int m_ImageCount = 1

 0 int m_TextureDimension = 2

 0 GLTextureSettings m_TextureSettings

  0 int m_FilterMode = 2

  0 int m_Aniso = 1

  0 float m_MipBias = 0

  0 int m_WrapU = 1

  0 int m_WrapV = 1

  0 int m_WrapW = 1

 0 int m_LightmapFormat = 0

 0 int m_ColorSpace = 1

 1 TypelessData image data (0 items)

  0 int size = 0

 0 StreamingInfo m_StreamData

  0 unsigned int offset = 715828144

  0 unsigned int size = 89478484

  1 string path = "resources.assets.resS"
`
![image](https://user-images.githubusercontent.com/42720004/50463552-5da30600-0941-11e9-9956-920618050fcc.png)

**Comment by thejeffreyallen** [comment]
This is because the actual image is stored in the .ress file. Use a different texture and import it as raw first, then import the new texture using plugins edit.
