### ISSUE TITLE
Bulk texture export

### ISSUE THREAD

**Issue by delm959** [DerPopo/UABE#26]
I saw somewhere that you can bulk export textures by selecting the textures you want then export to .png. The issue I'm having is that all the files a want to export have the same name (e.g. all of them are named face_ab.png) so when I export them I end up getting one png instead of the amount I selected originally as they are obviously overwriting eachother. 
Is there anyway around this? In the export plugin is there a way to check if the .png has the same name and if it does add a number to the file name as Windows does when there is a duplicate file?

**Comment by DerPopo** [comment]
Should work better with the next release. The only case it doesn't check is when there is e.g. "a" twice and "a_1", so one "a" would overwrite "a_1" or the other way round.
