### ISSUE TITLE
Can't open new .resource files

### ISSUE THREAD

**Issue by y0lopix** [DerPopo/UABE#268]
When I tried to extract assets from the latest version of the iOS game "Pixel Gun 3D", I discovered that .assets files have been replaced by .resource files and it is now impossible to open them. I get this error message:

Unable to read the bundle file! (Invalid file or unknown version?)

**Comment by jack980517** [comment]
.resource files are not asset bundles. They contain sound data, which is then referenced by the asset bundles.

**Comment by y0lopix** [comment]
That was right for the old assets format but now all sharedassetsX.assets and resources.assets are .resource files. It would mean that the game is composed of sound data only, and that's not the case.

Old assets:
![Screenshot](https://user-images.githubusercontent.com/13918281/53592609-f26eed80-3b96-11e9-8215-6fcd3170b80e.png)


New assets:
![Screenshot](https://user-images.githubusercontent.com/13918281/53592570-dd925a00-3b96-11e9-8583-5a6142224a47.png)

**Comment by y0lopix** [comment]
I just noticed that all assets files are missing in the new IPA, only .resource files are still there. Furthermore, both IPA files (new and old) are the same size but the new IPA data folder is only 1GB while it was in the previous IPA 2.8 GB. All .assets must be hidden somewhere in the IPA...
So that's not a UABE issue.

**Comment by jack980517** [comment]
Your situation might be what I encountered in #170

**Comment by y0lopix** [comment]
> Your situation might be what I encountered in #170

I'm in exactly the same situation. All the missing assets were actually in the data.unity3d file and UABE can uncompress and open this file without any problem. That explains why the uncompressed IPA is so small compared to the previous version of the game.

**Comment by ComputerFix** [comment]
Assets Bundle Extractor Unable not be read! Invalid or unknown file 100%

https://www.youtube.com/watch?v=sXq54Ovw1GE&feature=youtu.be&ab_channel=Xpirate04
