### ISSUE TITLE
The search function is absolutely useless

### ISSUE THREAD

**Issue by TA10S** [DerPopo/UABE#270]
![OGRfXN2W4t](https://user-images.githubusercontent.com/23386729/54656292-7122c080-4a9b-11e9-81ae-bd39e85a4cdc.gif)
How does it work?

**Comment by AndreaFaso** [comment]
You should use '*CZ75*' in the search field

**Comment by AndreaFaso** [comment]
You should use `*CZ75*` in the query field

**Comment by TA10S** [comment]
Oh, it's for exact searches. I guess that makes sense. Solved, thanks.
