### ISSUE TITLE
Sprite support

### ISSUE THREAD

**Issue by deathbypixel** [DerPopo/UABE#28]
Thanks for a great product! Is there a plugin for exporting assets of type Sprite? 

How do I write my own plugins?

Cheers

**Comment by DerPopo** [comment]
Each Sprite has one or two texture references. You can find the texture's file and path ids through "View Data", locate it in the asset list and export the texture as usual.

Plugins depend on an API which is still subject to change so almost every new release breaks them. Maybe I'll release it when it's in a near-final state though.

**Comment by DerPopo** [comment]
The new API contains the plugin interface and a sample plugin.
