### ISSUE TITLE
Some question about AudioClip file

### ISSUE THREAD

**Issue by Arfra-token** [DerPopo/UABE#284]
UABE is quite a useful tool,and it helped me a lot in mod-making.However,when I tried to edit AudioClip file,I found that the size of AudioClip file is usually about 100 bytes in UABE interface but the size of exported .wav file is usually dozens of MB. So what does the size of AudioClip file show on UABE interface mean?
Besides, are there any possible ways to modify AudioClip files?

**Comment by DerPopo** [comment]
AudioClip assets only are a reference to a .resource file, along with the start position and size of the embedded .fsb file (since Unity 5.x). Since the sounds are stored in FMOD sound banks (a proprietary format), UABE converts them to uncompressed .wav.

**Comment by Arfra-token** [comment]
Thanks for the explanation,It has bothered me quite a long time about the size of file.
