### ISSUE TITLE
How to extrat shader&Script?

### ISSUE THREAD

**Issue by MaNGOS-FAN** [DerPopo/UABE#29]
How to extrat shader&Script?

**Comment by 0x900x90** [comment]
Scripts stored in dll's. Shader you can extract as bin an then cut some bytes in the beginning and at the end of file. What do you want to do with shaders? From version 5.3 shaders stored in pre-compilled binary format.

**Comment by MaNGOS-FAN** [comment]
thanks! i want to learn some useful shader techniques so i can expand my arsenal and develop my own effects!
i extrated shader file and the file data is wrong.
Forgive my poor English ：)

**Comment by DerPopo** [comment]
Closing this issue.
https://github.com/DerPopo/UABE/issues/112
