### ISSUE TITLE
Decompression of 2018.4.4 file fails "Unable to decompress the bundle file!"

### ISSUE THREAD

**Issue by neobenedict** [DerPopo/UABE#299]
Decompression of a unity 2018.4.4f1 file fails with the not so helpful error message "Unable to decompress the bundle file!".

This file can be decompressed and extracted just fine in other unity tools like AssetStudio and uTinyRipper, but I need the repacking functionality of UABE.

File: 

Please fix, thank you.

**Comment by nesrak1** [comment]
Not sure why UABE isn't able to extract it but if all you need is an uncompressed bundle to open in UABE, this should do it:
[broken.unity3d.unpacked.zip](https://github.com/DerPopo/UABE/files/3628696/broken.unity3d.unpacked.zip)

**Comment by neobenedict** [comment]
> 
> 
> Not sure why UABE isn't able to extract it but if all you need is an uncompressed bundle to open in UABE, this should do it:
> [broken.unity3d.unpacked.zip](https://github.com/DerPopo/UABE/files/3628696/broken.unity3d.unpacked.zip)

Thanks, what tool did you use to do this?

**Comment by nesrak1** [comment]
The c# version of uabe here https://github.com/nesrak1/AssetsTools.NET. I'm not working on it anymore though.

**Comment by neobenedict** [comment]
> 
> 
> The c# version of uabe here https://github.com/nesrak1/AssetsTools.NET. I'm not working on it anymore though.

Hmm, thanks
Unfortunately I can't seem to repack it properly in UABE, the game keeps crashing. Is the decompression/unpacking symmetric, do you know? Can I code something to ensure the file is put back together in the same format?

**Comment by nesrak1** [comment]
As far as I know, the game shouldn't be able to be able to detect compression, but it might be able to hash the file. If it opens fine in other tools, most likely it's that and you'd have to look in the game code. If it doesn't open in other tools, uabe may have corrupted the bundle or something.

**Comment by neobenedict** [comment]
OK, it errors out in uTinyRipper with Import: System.Exception: Read 140 but expected 91, so UABE is corrupting the file.

**Comment by nesrak1** [comment]
If you can send the bundle, I can try to debug it

**Comment by neobenedict** [comment]
> 
> 
> If you can send the bundle, I can try to debug it

Here's a working bundle:
https://tearsinra.in/working.unity3d

If you simply open and resave the file, it gets changed and the game crashes.
If I manually edit the file in a text editor (I'm just changing those base 64'd strings) the patch is applied to the game fine, but I have to have the same length exactly I think. Will test.

Basically I'm just looking for a way to change those b64'd strings with another b64'd string of variable length.

**Comment by nesrak1** [comment]
When I opened both working and broken in UABE and saved, the files contents didn't change for me at all. They seem to be the same before and after saving.
On the other hand, both working and broken won't open in utinyripper but I think it might be a bug where it won't correctly read non-compressed bundles. It tries to compare the length of the whole header to decompressed size which is wrong (at least it is to uabe). With the lengths changed, the files open in utr now but won't open in either uabe.

[utr.zip](https://github.com/DerPopo/UABE/files/3629391/utr.zip)

**Comment by neobenedict** [comment]
> 
> 
> When I opened both working and broken in UABE and saved (no changes), the files contents didn't change for me at all. They seem to be the same before and after saving.
> On the other hand, both working and broken won't open in utinyripper but I think it might be a bug where it won't correctly read non-compressed bundles. It tries to compare the length of the whole header to decompressed size which is wrong (at least it is to uabe). With the lengths changed, the files open in utr now but won't open in either uabe.
> 
> [utr.zip](https://github.com/DerPopo/UABE/files/3629391/utr.zip)

What version of UABE? There are some clear changes for me.

**Comment by neobenedict** [comment]
OK, by some miracle, it's working properly after saving.

The initial bug still remains though.

**Comment by neobenedict** [comment]
I'm closing this as I wasn't calling flush final block on the decryption so a bit of the end of the file was missing (and I never noticed because everything extracted fine), strange how other tools worked fine but this one didn't, but it was a mistake on my end.
