### ISSUE TITLE
Some issues and suggestions

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#3]
- Texture plugin re-encodes picture, when you only want to change texture settings. Wrap mode for example.

- For some reason i cant open any *.unity3d file. Here is one for example. Can't open it both in XP and win7.
http://www29.zippyshare.com/v/x3f5BuCg/file.html

- Batch export/import would be nice. I don't know best way for this.

- Some data in mainData file shown wrong. For example Player Settings. When i manually changed runinbackground option in hex-editor, UABE showed it wrong. Personaly, i think there is no universal way to detect these settings for mainData files of different versions.

**Comment by DerPopo** [comment]
unity3d files are compressed files (their file header says UnityWeb). Currently only uncompressed (UnityRaw) are supported. I'm not sure how to decompress them but I can look into it.

The Unity 5 type database in the current release still is for 5.0.1f1. Even though there are only minor changes to each new Unity version, one change in a type (such as PlayerSettings) can make the whole asset dump invalid.
I wrote a tool that generates type databases from player .exes (using some reverse engineering magic I have to update for each release) but I have already created a database for 5.2.0f3 which I will release with the next UABE version.

I'll also look into the other two suggestions.

Thanks for the feedback!

**Comment by DerPopo** [comment]
I managed to decompress .unity3d files with the LZMA SDK, so I guess compressed .unity3d will also be supported in the next release.

**Comment by 0x900x90** [comment]
OK.

**Comment by Devlop-Studios** [comment]
i cant open the UABE it said MSVCR100.dll was not found plz help
