### ISSUE TITLE
Extract Monoscript

### ISSUE THREAD

**Issue by fattakhovmarat** [DerPopo/UABE#30]
Tried to extract serialized object from resources.
It has been detected as Monoscript Base. In attached screenshot you can see it.
In dump I see only names and property hash.
How can I get this serialized object?
Thanks.
![monoscript](https://cloud.githubusercontent.com/assets/17141907/13374361/7127b702-dd93-11e5-9571-21df674756c8.png)

**Comment by DerPopo** [comment]
You can double click the MonoScript Base item in order to see the rest in View Data.

The thing you are probably searching for is a MonoBehaviour, which contains serialized game data. So far only viewing the raw dump in a hex editor and looking at the serializable fields in the according script allows you to interpret the game data (note that there is a part of Unity first and the game data begins after that).

**Comment by fattakhovmarat** [comment]
Thanks, but in details I see the same data as from a dump.

I'll try to find out. I look for just one string property.

**Comment by fattakhovmarat** [comment]
Found nothing in MonoBehavior. Have been searched by GameObject = BuildSettings in MonoBehavior fields.

**Comment by fattakhovmarat** [comment]
Have found item with type BuildSettings, but nothing useful yet.
![image](https://cloud.githubusercontent.com/assets/17141907/13378619/f4a5ddbe-de1c-11e5-89d0-5bf72db03581.png)

**Comment by fattakhovmarat** [comment]
Is that serialized fields in screenshot?
Because I see sources and don't see this fields in them.
![image](https://cloud.githubusercontent.com/assets/17141907/13378713/def6ee4c-de1f-11e5-9bfd-17a2714f063d.png)

**Comment by DerPopo** [comment]
Everything Unity stores in its bundles is serialized data, but there are Unity-specific and game-specific types.
You are probably looking for MonoBehaviours (in this case, the game's data begin with meshes).
If you want to find out which script a MonoBehaviour is for, just open the m_Script tree, [view asset] and Base and you'll see the name and assembly of the script.
![monobehaviour](https://cloud.githubusercontent.com/assets/8328510/13403261/7383650a-df14-11e5-87a1-81cacb9e6062.PNG)

**Comment by DerPopo** [comment]
MonoBehaviours will be fully supported in the next release.

**Comment by AndreiGTA** [comment]
How to extract monoscript in uabea?
