### ISSUE TITLE
New Texture Masks to Old Texture

### ISSUE THREAD

**Issue by mekellioz** [DerPopo/UABE#316]
When I edit a Texture2d file, it gets masked to the original image
![image](https://user-images.githubusercontent.com/59541435/71785939-9acdb980-2fd3-11ea-8b2f-bcd78e171809.png)

I stayed well within the image size, as you can see in this screenshot
![image](https://user-images.githubusercontent.com/59541435/71786077-a7eba800-2fd5-11ea-9fd1-a44de8a3fcc8.png)

**Comment by DerPopo** [comment]
Since UABE does not do any masking, I suspect the image editor left the original data in the invisible part. Also, the alpha channel is dropped when importing to texture formats without alpha support. If it's DXT1, use DXT5 instead, or if it's a RGB/BGR/... use the variant with A.

**Comment by mekellioz** [comment]
This is the first file I used originally, I had it set to DXT5 but also tried ARGB32
![title0](https://user-images.githubusercontent.com/59541435/71788048-e0e34700-2fec-11ea-9ef1-270e2fde446e.png)

I re-edited the image saving after deleting every invisible layer, using the fill bucket on every layer at 0 tolerance to make 100% there was nothing but the image on any layer, tried .tga and .png again on both DXT5 and ARGB32, and it is still happening unfortunately

**Comment by DerPopo** [comment]
That's strange. Maybe there's some old mip map floating around along with the new texture.

Is the upper broken screenshot directly from Texture2D export? If it's from in-game, it may be related to cutout by the Sprite mesh, in case there is a corresponding Sprite asset.

**Comment by mekellioz** [comment]
It's from in game, and looking through the files there is a sprite asset. So I am guessing that's it. I have no clue on how to change that to match the new image.

My assumption is, the Texture2d is displaying over the old Sprite asset? Is there a way to fix that?

**Comment by 0x900x90** [comment]
You should understand what is sprite first. It uses a part of texture. I recommend you to use AssetStudio. You can check how your sprite looks after texture modification. You can fix sprite using UABE after that. Use export/import dump and change coordinates if needed.

https://github.com/Perfare/AssetStudio

**Comment by mekellioz** [comment]
It's smaller in dimension, but that's about it. It's not showing it as cut off. I'll look into making a new sprite to replace the old one when I have time, thank you

![image](https://user-images.githubusercontent.com/59541435/72037754-34fc5e80-326d-11ea-8307-6fb6a94d17a7.png)
