### ISSUE TITLE
resources.assets.resS and resources.resource

### ISSUE THREAD

**Issue by shamashii** [DerPopo/UABE#32]
Recently I met a game which seemed resources are not in one resources.assets file, there were two other files correspond it:  resources.assets.resS(bigger file size) and resources.resource (bigger file size)
any updates? I'll post game link if need.

**Comment by DerPopo** [comment]
The data of some assets (AudioClip/Texture2D) must/can be stored in an external file (and are referenced by the asset). Exporting a Texture2D should also work with external files (only if the .assets file is opened).
In case they add such a thing for other formats covered by UABE plugins (such as Mesh), I would need to add support for these cases.

**Comment by son1cman** [comment]
If you can support this case will be cool!!! its like unity 5.3.1p4 its creating this .ress files. Your tool its the only tool working with 5.3.1p4 i think
