### ISSUE TITLE
.assetbundle format

### ISSUE THREAD

**Issue by flamestream** [DerPopo/UABE#33]
I've been using this tool successfully over different projects until I stumbled upon a new `.assetbundle` format which, when attempting to open it, renders the application unresponsive. 
Is it a valid use case? If so, are there any plans to add support for it?

**Comment by DerPopo** [comment]
Which game/program is that file from?

**Comment by flamestream** [comment]
It's from jp.mbga.a12010716.lite.
Note that the assets in the apk are viewable.
The assets in question are however downloaded separately in-game and placed in the SD card.
I can provide you a sample if needed.
