### ISSUE TITLE
[Request] Scripts, Shader extract feature

### ISSUE THREAD

**Issue by damh0503** [DerPopo/UABE#36]
I want scrips and shader extract feature.
Asset Bundle Extracter is the best tool kit, but I'm really sad that I can only extract sounds and models, textures...:(

**Comment by DerPopo** [comment]
To export scripts, I recommend using tools like Telerik JustDecompile. Scripts in .assets files are just references to the classes in the .dll assemblies.
In new Unity versions, the actual shader code is stored in some compressed bytecode format (or something like that, for some reason it has lots of 00s even though the field names suggest it's compressed). I'll look into 1. decompressing and 2. translating it into something useful but I can't promise much at this point.

**Comment by damh0503** [comment]
Thanks :)

**Comment by DerPopo** [comment]
MonoBehaviour extraction will be in the next release, Shader (https://github.com/DerPopo/UABE/issues/112) probably won't.
