### ISSUE TITLE
Excess samples created in extracted sounds.

### ISSUE THREAD

**Issue by xEvanrocks** [DerPopo/UABE#37]
I've been extracting the sounds from the recent title "The Lab" and noticed something after extracting samples, looped wave files have a very audible pauses at the end of each file, these pauses range from 3000 - 4095 samples from what I've seen and the length seems to be random. The most plausible solution would be to trim the files, from the end until a value not equal to 0 is met.
If a patch could be made that would be great.

I'll provide 6 raw wave files in the zip as examples.

inerior_03.wav contains 3713 extra samples.
inerior_04.wav contains 3947 extra samples.
inerior_05.wav contains 3524 extra samples.
conveyorBelt_01.wav contains 4095 extra samples.
computers_01.wav contains 4095 extra samples too for some reason.
chopper_engine_lp_02.wav contains 3333 extra samples.

[samples.zip](https://github.com/DerPopo/UABE/files/211900/samples.zip)

**Comment by DerPopo** [comment]
It seems like FMOD buffers a default amount of samples, which it all writes to the .wav without necessarily having a channel playing. Setting that buffer size to 1 sample made the size exact, I'll probably use 4096 samples or less if there are less than that remaining.

**Comment by DerPopo** [comment]
I switched from playing the sound to a file to using FMOD::Sound::lock to get the decompressed data. Now everything seems correct. The fix will be in the next release.
