### ISSUE TITLE
.utage single resource files

### ISSUE THREAD

**Issue by xaeroak15** [DerPopo/UABE#38]
Hello, I recent met a VN game [which](http://magnet:?xt=urn:btih:D8E3F5D46B432CA0B06C50AC453DE34AC821588C) major images are separated in originalname.ext.utage format eg: bg.png.utage. It's high appreciated if you have time look at this case.

**Comment by DerPopo** [comment]
Utage seems to be some text adventure engine built upon Unity but these .png.utage files are not actually Unity files.
