### ISSUE TITLE
Unity 5.4

### ISSUE THREAD

**Issue by tetTris11** [DerPopo/UABE#39]
would you be able to update this to work with Unity 5.4 assets? although its still in beta iv already found something that uses it: Valve's collection of VR demos "The Lab", its free on Steam. if you don't have Steam i can send you over some files to help

**Comment by DerPopo** [comment]
I couldn't find any problems with it, Textures, Meshes and AudioClips are exportable. Just select the U5.3 type database, it should work for most asset types.

**Comment by tetTris11** [comment]
strange, everything i try either comes out corrupted or causes the program to crash, well i also think i'm using an older version, i know nothing of code compiling and can't find a download of a compiled version even if there is one. would you be able to pull some assets out for me?

**Comment by DerPopo** [comment]
Doesn't 1.9 start/work properly? If so, I'd be keen to fix it.

**Comment by tetTris11** [comment]
i'm not sure, i have no idea how it works, am i missing some sort of .exe or .bat file? does it need to be put into some sort of code compiler? but as for an example of some of the files: http://i.imgur.com/mp0DGTA.png, this is "atlas_shoulder_2k" found in "level11"

**Comment by DerPopo** [comment]
The 1.9 API has header files for the .assets/bundle file tools. In case you downloaded the API, it is not the tool itself.

**Comment by tetTris11** [comment]
well that would explain it, where does one get the tool itself?

**Comment by DerPopo** [comment]
The link above the 1.9 API (with 32bit and 64bit release) is the right one.

**Comment by tetTris11** [comment]
oh wow, how did i miss that? but it works perfectly thanks <3
