### ISSUE TITLE
Error, Unable to read the bundle file

### ISSUE THREAD

**Issue by roboserg** [DerPopo/UABE#393]
Does this tool work for Unity 2020.1? I am trying to extract files from my own game. I messed up github desktop client and lost 2 weeks of work with my game. Fortunately, I have a build from today, so all my files are in the build version of the game. But using this tool gives me an error:
https://i.imgur.com/6lULMcQ.png

I am trying to open .asset files from the build folder of my game

**Comment by Lethalchip** [comment]
No, unfortunately it doesn't work for 2020. 

Asset Studio does however: https://github.com/Perfare/AssetStudio
It can't quite get to the same level of detail that UABE did, but it's better than nothing?

**Comment by roboserg** [comment]
Thanks! I was able to retrieve the commit using git in the console, the commit was hidden. Saved the 2 weeks of work, it was close :)
