### ISSUE TITLE
Please add 2019.4.0f1 version

### ISSUE THREAD

**Issue by orangespoons** [DerPopo/UABE#397]
Files can open in AssetStudio, but not in UABE.
I think UABE doesn't support 2019.4.0f1.
Can you update this?
Thanks.

**Comment by mskgroup** [comment]
[Here solved your problem#410](https://github.com/DerPopo/UABE/issues/410)

**Comment by orangespoons** [comment]
> [Here solved your problem#410](https://github.com/DerPopo/UABE/issues/410)

Thanks!
