### ISSUE TITLE
No plugins (Dani's Karlson Game)

### ISSUE THREAD

**Issue by BurAndBY** [DerPopo/UABE#399]
![image](https://user-images.githubusercontent.com/48630651/106591108-eba93c00-655e-11eb-9213-5e533a7dc2c9.png)

**Comment by Igor55x** [comment]
### UABE does not currently contain plugins for exporting the Material assets.
### So that would be a good improvement.

**Comment by BurAndBY** [comment]
> ## UABE does not currently contain plugins for exporting the Material assets.
> ### So that would be a good improvement.

IT WORKED 3 SECONDS AGO BEFORE THIS

**Comment by Igor55x** [comment]
> > ## UABE does not currently contain plugins for exporting the Material assets.
> > ### So that would be a good improvement.
> 
> IT WORKED 3 SECONDS AGO BEFORE THIS

**What do you mean? It doesn't work with Material assets. Maybe you exported a different asset with the plugins?**

**Comment by BurAndBY** [comment]
> > > ## UABE does not currently contain plugins for exporting the Material assets.
> > > ### So that would be a good improvement.
> > 
> > 
> > IT WORKED 3 SECONDS AGO BEFORE THIS
> 
> **What do you mean? It doesn't work with Material assets. Maybe you exported a different asset with the plugins (e.g. the Mesh asset)?**

UHHHHHHHHHH

**Comment by bustercody3** [comment]
> > > > ## UABE does not currently contain plugins for exporting the Material assets.
> > > > ### So that would be a good improvement.
> > > 
> > > 
> > > IT WORKED 3 SECONDS AGO BEFORE THIS
> > 
> > 
> > **What do you mean? It doesn't work with Material assets. Maybe you exported a different asset with the plugins (e.g. the Mesh asset)?**
> 
> UHHHHHHHHHH

It works with texture2D files but not materials.
