### ISSUE TITLE
UABE not working correctly on unity games other than 7dtd

### ISSUE THREAD

**Issue by joyello** [DerPopo/UABE#4]
Hi there. I am trying to mod a game made with unity 5 and I tested any tool I could find on the internet for days.
Your tool is the one who works best, because it can open both level/maindata files and .assets, but it doesn't work correctly meaning that I can only export one file per time. Is there a fix for that?

I also found some game files which contain item stats (defenses, damages and so on), but I can only export them to .dat (RAW) and I can't read the numbers.. do you know how to?

And last thing, is out there a plugin to convert movietextures?

Thanks! Great job on UABE.

**Comment by DerPopo** [comment]
I could add an option for selecting multiple assets at a time to export (or to import files to). Currently it only supports one item at a time.

Exporting game specific asset types is possible but requires extracting the necessary type information from the game's assemblies (usually Assembly-CSharp.dll). I might look into doing such a thing.

MovieTextures seem to be Ogg Theora encoded (.ogv). I could look into creating a plugin for it.

**Comment by DerPopo** [comment]
Added a MovieTexture plugin, it will be released with the next version.
