### ISSUE TITLE
UABE Update for latest Unity?

### ISSUE THREAD

**Issue by short-reviews** [DerPopo/UABE#419]
Hey! I'm having the same issue that others have reported for opening Among Us .asset files. 

Innersloth has updated it to the latest version of Unity, so UABE cannot open the newer updates.

![CantOpenAmongUs](https://user-images.githubusercontent.com/83087756/115908512-42c0fd80-a438-11eb-9428-e2bc2b307230.jpg)

Is it hard to update this tool? I know a lot of people have already asked for it, but if you could update it would be so cool! Much of the community is missing their modding, me too. :(

**Comment by A-nonymous027** [comment]
New UABE is coming (#410) but it's still in progress.

**Comment by short-reviews** [comment]
> New UABE is coming (#410) but it's still in progress.

Really? That's awesome to hear! I don't think I have enough time to learn C# to try and figure out how to mod the game again.
