### ISSUE TITLE
Issue with Texture2D plugin

### ISSUE THREAD

**Issue by delm959** [DerPopo/UABE#42]
I can currently export DXT5 texture formats to .png fine but when I try to export a ETC_RGB4 texture format the the asset extractor just freezes.
![image](https://cloud.githubusercontent.com/assets/11843578/15004097/ffff7922-1206-11e6-8eeb-5f21bc161ceb.png)
![image](https://cloud.githubusercontent.com/assets/11843578/15004109/156daebe-1207-11e6-9c5a-8a6a611d5c8b.png)

**Comment by DerPopo** [comment]
Which game is it from? In order to test it, I need a sample asset (the raw Texture2D asset is enough) + the .resources file (if existant)

**Comment by delm959** [comment]
I can send you the asset file if you like and point you to the problematic Texture? Do you have a email or something I can contact you on?

**Comment by DerPopo** [comment]
You can also upload the raw data as an attachment here.
Here's a test file with a ETC_RGB4 compressed texture. I found no issues exporting it. If it does have an issue on your system, double-check if you have the Visual C++ 2013 Redistributable installed.
[test.zip](https://github.com/DerPopo/UABE/files/266307/test.zip)

**Comment by delm959** [comment]
I had no trouble exporting your test asset either, must be something else wrong with it. Looks like I have it installed as well...
![image](https://cloud.githubusercontent.com/assets/11843578/15310607/baeaf30e-1c45-11e6-824b-24b8f0fbfb86.png)
Below is the asset file. There are a lot of images in there but the one I'm having issues with has the Name 'face_ab' and Path ID '247599808996...'
[Assets.zip](https://github.com/DerPopo/UABE/files/267387/Assets.zip)

**Comment by DerPopo** [comment]
Found the bug. It was because the mipmap count was set to -1 because that engine version has no m_MipCount field. The negative value was then passed like a positive value, resulting in the number  4294967295. Theoretically, it might complete somewhen but instead here's a small fix :

[TexToolWrap.zip](https://github.com/DerPopo/UABE/files/268192/TexToolWrap.zip)

**Comment by delm959** [comment]
Awesome! Thanks mate, you're a legend :)

**Comment by delm959** [comment]
I have just noticed an issue with the extracted ETC_RGB4 images though. The backgrounds should be transparent but they are coming out all strange. Here are some examples...

![face_ab_121](https://cloud.githubusercontent.com/assets/11843578/15447380/cfa82aee-1f94-11e6-82f7-633a92783899.png)
![face_ab_133](https://cloud.githubusercontent.com/assets/11843578/15447383/dcb1f3fa-1f94-11e6-89f2-662a62e3a8bf.png)

Not sure why those strange lines are showing up, I have no issue with the DXT5 textures.
Try a face_ab texture from this file..


[CAB-ee7232b2f4b570f5081d9068e0ec5f51.zip](https://github.com/DerPopo/UABE/files/275779/CAB-ee7232b2f4b570f5081d9068e0ec5f51.zip)

**Comment by DerPopo** [comment]
ETC_RGB4 has no alpha channel. It also isn't needed because Unity creates sprite meshes so the "transparent" area won't be displayed.

**Comment by beytrade** [comment]
@DerPopo Hi, This tool is really great! I have one question. The following attached unity3d file should contain a image with color data, but when extracted it's converted to the alpha 8 transparent image, and color data is lost.

- I tried another texture format, but the result did not change.
- I doubted that sprite has a color table, but I could not convert sprite data to color table.
- Is this a bug of UABE related to Texture2D?

http://assets.mirror.hekk.org/v3/ios/units/illust/5001_1705630752.unity3d

env: UABE v2.1c, Win7, VC++2013 installed

**Comment by DerPopo** [comment]
It does only contain a 8 bit (1 byte) texture. The image size of 2097152 is exactly 2048*1024, so there is not more data than what UABE extracts.
Looking at the texture, it seems like the game has its own way to map the color data on top of the grayscale texture. The left half is a high resolution grayscale and there are three 1/4 size images, likely representing two different color channels (left half) and the alpha channel. The third color channel can be calculated from the grayscale and the two other channels.

**Comment by beytrade** [comment]
@DerPopo That make sense! It was not a bug. I'm sorry.
I wrote the convert script based on your advice and succeeded in generating colors. But the output image is a little different in color. Please give me a clue :pray:
```python
import cv2

img = cv2.imread('texture2d.png', cv2.IMREAD_UNCHANGED)
height, width = img.shape[:2]

for w in range(0, width):
    for h in range(0, height):
        if w < 1024 and h < 1024:
            G = img[h, w][3]  # left grayscale
            B = img[h/2, 1024+(w/2)][3]  # right top
            R = img[512+(h/2), 1024+(w/2)][3]  # right bottom
            A = img[512+(h/2), 1024+(1024/2)+(w/2)][3]  # alpha
            img[h, w] = [B, G, R, A]

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by DerPopo** [comment]
I couldn't find out the actual method either, the conversion you have is the best I could find so far.

**Comment by guliii41** [comment]
> Found the bug. It was because the mipmap count was set to -1 because that engine version has no m_MipCount field. The negative value was then passed like a positive value, resulting in the number 4294967295. Theoretically, it might complete somewhen but instead here's a small fix :
> 
> [TexToolWrap.zip](https://github.com/DerPopo/UABE/files/268192/TexToolWrap.zip)

Hey, I was having the same problem. I wanted to try your fix but I don't know what to do with .dll file you attatched. Please can you guide me where to put it?
