### ISSUE TITLE
please help me thanks.

### ISSUE THREAD

**Issue by haowangha** [DerPopo/UABE#45]
@DerPopo texture format no 32bit-A8R8G8B8 choice

**Comment by haowangha** [comment]
Transparent background PNG import does not support

**Comment by DerPopo** [comment]
ARGB32 is the same as A8R8G8B8. I couldn't find any issues importing transparent .pngs.
If you edited the .png, make sure it was saved as 32bit.

**Comment by haowangha** [comment]
@DerPopo 
I confirmed that my picture is 32, I put the original program LOGO import and export will not be the same.

**Comment by DerPopo** [comment]
Closing this. In case this issue still isn't solved, feel free to reopen this.
