### ISSUE TITLE
Batch export AudioClip

### ISSUE THREAD

**Issue by Ralphilius** [DerPopo/UABE#46]
Hello,

Is there any way I can batch export the AudioClip in a bundle file? I can extract a single file, but it's inconvenient since the file name isn't taken over to the save screen. Moreover, there are hundreds of files to be exported, so it is a pain to do it one by one. This could be helpful with other type of data as well.

This tool is the only one working right now.

Thanks,

**Comment by DerPopo** [comment]
The plugin does support batch exporting, just select multiple files (all must be the same type) using ctrl or shift.

**Comment by Ralphilius** [comment]
Thank you.. I got it working :)
