### ISSUE TITLE
Unable to open newer sharedassets(#).assets files.

### ISSUE THREAD

**Issue by FosterOrionGH** [DerPopo/UABE#465]
I was wondering if there was another program to modify sharedassets(#).assets files? I'd like to mod some newer games, but the files don't open properly. Thanks.

**Comment by Igor55x** [comment]
> I was wondering if there was another program to modify sharedassets(#).assets files? I'd like to mod some newer games, but the files don't open properly. Thanks.

Here are two alternative programs: [UAAE](https://github.com/Igor55x/UAAE) and [UABEA](https://github.com/nesrak1/UABEA).

**Comment by woctezuma** [comment]
Also, [AssetRipper](https://github.com/AssetRipper/AssetRipper).
