### ISSUE TITLE
Unable to open streamed data file.

### ISSUE THREAD

**Issue by helixion** [DerPopo/UABE#47]
Trying to extract a texture from resources.assets using the plugin but keep getting the same error (Unable to open streamed data file), followed by an unable to convert texture data.

**Comment by DerPopo** [comment]
Is the resources.assets file opened in the same folder as the resources.resource file?

**Comment by kkero77** [comment]
please add support mp3 ogg file format

**Comment by Drachenbauer** [comment]
> Is the resources.assets file opened in the same folder as the resources.resource file?

I have this issue too but both files are in the folder.
