### ISSUE TITLE
[Request]Open multiple files at once

### ISSUE THREAD

**Issue by delm959** [DerPopo/UABE#49]
I currently have to sort through hundreds of asset files to check whats inside them. Is there a way you could add an option to open multiple files at once?

All the files are similar to the file I sent you a few weeks ago.

**Comment by DerPopo** [comment]
This might be a thing I can add to the command line as it wouldn't properly fit to the UI.

**Comment by delm959** [comment]
Sure that would be great, it would save me a lot of time. Is it hard to implement?

**Comment by DerPopo** [comment]
You can now select multiple .assets files in the open file dialog.
If the files are in a <gamename>_Data folder, it's possible that most of the .assets are dependencies of the mainData / globalgamemanagers files. In this case, only opening that file is enough.
