### ISSUE TITLE
Unable to export sound with AudioClip plugin on Win10

### ISSUE THREAD

**Issue by magicalz** [DerPopo/UABE#50]
First I'll thanks author for this useful tool.
I just upgrade my system from Win8.1 to Win10, and the export sound from AudioClip plugin behavior cannot work(version 1.8.1, both x86 and x64), it prompts:"Unable to create a sound object". 
Version 1.8.1 works fine on Win8.1 system.
And version 1.9 cannot work either on Win8.1 or Win10, click the plugin "export sound" without any response.
The unity3d file is a BGM of UnityFS 5.3.5f1 format.

**Comment by magicalz** [comment]
Here is the file: https://mega.nz/#!NYchDLqD

**Comment by DerPopo** [comment]
It will be fixed with the next release, at least the file works with the current development version.
It might be related to this issue, and I wrote a workaround there :
https://github.com/DerPopo/UABE/issues/44

**Comment by magicalz** [comment]
Hi, this is actually a different issue with #44. 
It maybe caused by encoding, when the tool invokes AudioClip plugin, it needs select a folder, which only support ASCII charset, if the folder's name contains non-ASCII character, it will prompt:"Unable to create a sound object". I change to another folder and everything is good.
Tested ok using version 1.8.1(both x86 and x64).
Version 1.9 has the #44 issue.

**Comment by DerPopo** [comment]
That's another bug. Basically, I passed UTF8 file names to ASCII functions in some instances. It's already fixed for the next release.
