### ISSUE TITLE
Why i can't open assetbundle ?

### ISSUE THREAD

**Issue by wangjianpeng** [DerPopo/UABE#51]
I find a game dictionary and find some files liek Configs/txtfile.pk. Then i  reflector the assembly-cshapr.dll , get the code Assetbundle.loadfromfile("Configs/txtfile.pk")  (i dont  past the exactry code that the method parameter  ) . then i create a new unity proeject, use the same method, and fill the file path . why i can't get the asset ,  it's always null and not tell me error message on unity 4.x . at last i try unity 5 project with the same code. it tell me the can't find header . so i sure this asset bundle is create by untiy 4.x . Why the origina game assembly-csharp can use the method to load assetbundle, but i can't use is.  i never see the assetbundle encrypt code in the assembly -csharp dll . the assetbundlefile is extend with .pk even i rechange the extend with .assetbundle. it does no help.
and i can't open the file with **this tool**.or may be the game developer deencrypt all the bundle after launch game ,and then just use createfromfile to load the finally bundles ?

**Comment by DerPopo** [comment]
Could you upload one of these files? My guess is that the game uses a very old Unity version that neither Unity 4/5 nor UABE support.

**Comment by wangjianpeng** [comment]
no problem , it confused me these day,  i still dont  know which step is mistake.


I also load the unityengine.dll with the game, but i dont know which version ti is .

**Comment by DerPopo** [comment]
It indeed looks like the file was compressed and/or encrypted.
At least it's not the most up to date Unity version because NetworkView is not deprecated yet. You can look up the actual version in the output_log.txt, it should be somewhere at the top.

**Comment by wangjianpeng** [comment]
i find the output logfile, get the version is  engine version: 4.6.9f1 (44099fd26189) .then i redownload unity 4.6.9 setup , after install it. i use assetbundle.creatfrom file , but it still return null .  so strange

**Comment by 0x900x90** [comment]
As DerPopo allready wrote, your file is packed or encrypted. You can open it in any hex-editor and see that it does not contain standart assets bundle header.
