### ISSUE TITLE
*.unity3d and *.bytes files issue

### ISSUE THREAD

**Issue by DooMGuy87** [DerPopo/UABE#53]
I´m having serious problems trying to open these files. These files belong to an android game called "Sailor Moon Drops" and these files are dowloaded atomatically by the app.
The issue is that UABE Goes not responding when trying to open any of these .unity 3d files or a file called "AssetBundleDictionary.txt.bytes", but thats not all, while not responding, UABE starts to slow really bad my laptop, and even if close it, my laptop continues really slow at the point that I have to restart it. I have Windows 8.1 x64 if it helps.
The most strange thing is that I can view and export all the assets in the main apk but not the downloaded assets (.unity3d).
Thanks in advance.

**Comment by DerPopo** [comment]
The bytes files probably are a custom file format of that game. The unity3d files possibly are compressed/encrypted by the game but I can't tell if that's the reason.
I did some improvements to the detection whether the opened file is a supported Unity file format, so it probably won't freeze in an almost endless loop anymore.

**Comment by DooMGuy87** [comment]
Ah i see... 
That´s make sense, since if I wanted to open a not supported file, the program just didn´t open it, but it gave that endless loop just when trying to open these files... Too bad i can´t open these files, oh well.
BTW thank you for making this amazing tool!

**Comment by 0x900x90** [comment]
DecryptRJ128 function is used for decryption. If you know how to use decompillers and can use Microsoft visual studio, then you can write simple utility for decryption.
