### ISSUE TITLE
Unable to open the streamed data file (2)

### ISSUE THREAD

**Issue by iruzer** [DerPopo/UABE#54]
Unable to open the streamed data file when export sound with file with split resources.
(yyy.resource.split0 and yyy.resource.split1)

**Comment by DerPopo** [comment]
I'll take a look at it. It should be easy to fix though.

**Comment by iruzer** [comment]
if you want sample, i will upload it.

**Comment by iruzer** [comment]
If you want sample, i will upload it. 
maybe it could help you.

**Comment by DerPopo** [comment]
Can you confirm if it works now?

**Comment by iruzer** [comment]
it is work. thank you.
*closing
