### ISSUE TITLE
Can't Open V5.3.5 Unity3d Compressed File

### ISSUE THREAD

**Issue by edisonlin1030** [DerPopo/UABE#56]
https://drive.google.com/open?id=0B5xNbu1SMTG-R3phbW5sU1MyclU
I opened with Unity Assets Bundle Extractor 1.9 and it doesn't work

**Comment by 0x900x90** [comment]
I can't open *.doc, *.avi etc files with UABE. Why do you think it have to open your file?

**Comment by edisonlin1030** [comment]
My apologies, the data attached is a v5.3.5 compressed unity3d file.
Issue title is changed as well

**Comment by DerPopo** [comment]
The compression is done by the game itself, else the bundle header would be visible. In this case, a decompress tool for the compression type the game uses should be used first. You could also copy the decompress code from the game using one of many .net decompilers.

**Comment by edisonlin1030** [comment]
Thanks for the hint, now I can decompress the file with UABE
