### ISSUE TITLE
Some annoying issues.

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#57]
When i use import raw option, imported file stays blocked after import. I can't change it and reimport again.

I can't delete several assets at once. Something wrong happens with bundle file after this operation. I can delete asset, save bundle, close it. After that i have to do this with another asset.

**Comment by DerPopo** [comment]
I changed it so it reads the file and closes it after pressing the Import Raw button (except if it's out of memory).
The delete bug will be fixed in the next version.

**Comment by 0x900x90** [comment]
Maybe it's Windows XP problem with blocked file. This allready happened before with another software.

**Comment by DerPopo** [comment]
Should be fixed now.

**Comment by Yuuyatails** [comment]
@0x900x90 : Sorry for interruption, but how you are able to make the UABE 2.0b to run on Windows XP? I am just curious.

(I don't have any complier at the moment unfortunately.)

**Comment by DerPopo** [comment]
Here's the hotfix : https://github.com/DerPopo/UABE/issues/66#issuecomment-242350180

**Comment by Yuuyatails** [comment]
@DerPopo : Just the hotfix itself won't work. It shows me the 'SetThreadErrorMode could not be located in the dynamic link library KERNAL32.dll' error.

I just don't know how to rename the SetThreadErrorMode to SetErrorMode in the AssetsTools.dll file since I don't have Visual Studio installed.

**Comment by DerPopo** [comment]
[AssetsBundleExtractor_2.0b_XPFix2.zip](https://github.com/DerPopo/UABE/files/478612/AssetsBundleExtractor_2.0b_XPFix2.zip)
I had already forgotten about the SetThreadErrorMode issue. I've added a fallback to SetErrorMode but I haven't tested it in XP.
The function is used to prevent messages like it can't start because it can't find msvcr120.dll, so nobody gets it from a "trustworthy" dll download site (instead, only some mobile texture formats won't work with the Texture2D plugin).

**Comment by Yuuyatails** [comment]
@DerPopo : Sorry, but it doesn't fallback to SetErrorMode as he fix you made still causes the very same 'SetThreadErrorMode could not be located in the dynamic link library KERNAL32.dll' error while I'm trying to run it.

If you are curious. I am on Windows XP Professional SP3 32-bit. (I wanted a new PC with a newer OS, but I don't have enough money to brought one.)

**Comment by DerPopo** [comment]
Next try :
[AssetsBundleExtractor_2.0b_XPFix3.zip](https://github.com/DerPopo/UABE/files/483385/AssetsBundleExtractor_2.0b_XPFix3.zip)
I still called the normal SetThreadErrorMode if it's present, which of course still creates the import dependency.

**Comment by Yuuyatails** [comment]
@DerPopo : It no longer shows the 'SetThreadErrorMode could not be located in the dynamic link library KERNAL32.dll' error, but instead it shows the 'GetErrorMode could not be located in the dynamic link library KERNAL32.dll' error.

**Comment by DerPopo** [comment]
Next try :
[AssetsBundleExtractor_2.0b_XPFix4.zip](https://github.com/DerPopo/UABE/files/483457/AssetsBundleExtractor_2.0b_XPFix4.zip)
Seems like even GetErrorMode is not in XP, while the name suggests it is.

**Comment by Yuuyatails** [comment]
@DerPopo : After applied the 4th fix, the application is now running smoothly and I haven't encounter any issue so far.
