### ISSUE TITLE
Export dump in API

### ISSUE THREAD

**Issue by nesrak1** [DerPopo/UABE#58]
Is there any way to export dump in the API?

Also, I don't have and can't install VC++ 2010, and don't have a VM to run it on. Any way to update it to a later version?

**Comment by nesrak1** [comment]
Problem solved:
https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor/page8&p=459961#post459961

I still cannot compile it though.

**Comment by DerPopo** [comment]
What are the compiler errors? The incompatibilities between different C++ compilers' standard functions usually only cause runtime errors.

**Comment by nesrak1** [comment]
Any time I used anything that with the API that was FILE related would cause it to say "Microsoft Visual Studio C Runtime Library has detected a fatal error in APITEST.exe"
```
	FILE *pFile = fopen("C:\\Users\\nesrak1\\Documents\\ModdingTest\\Build\\KnifeTest_Data\\sharedassets0.assets", "rb");
	
	AssetsFile assetsFile(AssetsReaderFromFile, (LPARAM) pFile);
	
	AssetsFileTable assetsFileTable(&assetsFile);
```
It tells me it stops when I create AssetsFileTable, but if I remove that it tells me it stops on pFile close.
This is with VS 2015.

**Comment by DerPopo** [comment]
The FILE* passed to the precompiled AssetsReaderFromFile must be created with the VS 2010 Release libraries. You could also create your own reader compiled with VS 2015 to bypass that limitation. In the current release of the API, there still are some functions that can't easily be used with other compilers (especially if they use std::vector). Some of these will be changed so they take the raw array and a size parameter.
Here's the AssetsReaderFromFile code :
```
QWORD AssetsReaderFromFile(QWORD pos, QWORD count, void *pBuf, LPARAM par)
{
	if (pos != -1)
	{
		fpos_t fpos = (fpos_t)pos;
		if (fsetpos((FILE*)par, &fpos) != 0)
		{
			memset(pBuf, 0, (size_t)count);
			return 0;
		}
	}
	return fread(pBuf, 1, (size_t)count, (FILE*)par);
}
```

**Comment by nesrak1** [comment]
Thanks, it compiled perfectly now.

**Comment by nesrak1** [comment]
I guess I am a little confused with the read data thing in the link above.
You say to select the ClassDatabaseType that I need, but what is a ClassDatabaseType? And how do I use it?

**Comment by DerPopo** [comment]
First, export a type database with UABE (Options -> Edit Type Package -> Select a Unity version and export).  You can then open it with the ClassDatabaseFile class. The only problem is that ClassDatabaseFile has a std::vector of ClassDatabaseTypes, which likely won't be usable in VS 2015 without any classes copied over from 2010. 
Go through the vector of ClassDatabaseTypes and look for the right classId. Then, create an AssetTypeTemplateField (AssetTypeClass.h) and call FromClassDatabase with a pointer to the ClassDatabaseFile, the ClassDatabaseType and 0 for fieldIndex. With this, you can create an AssetTypeInstance (baseFieldCount = 1, ppBaseFields = &pBaseField) and call GetBaseField.
The AssetTypeValueField returned is the base field as in the asset view. To the [] operator (needs pointer dereferencing if you put multiple in a row) or the Get function, you can either pass a child field name or an index (for index 0, you'll have to write (DWORD)0).
If a child wasn't found, it returns a "dummy" value field so you can safely put multiple []s/Gets in a line. Afterwards, you can call IsDummy before using it. GetValue either returns a valid AssetTypeValue* (for any valid field that has no children) or null. 
AssetTypeValues have functions for every data type except for signed/unsigned Int8/Int16, for which you need the AsInt/AsUInt functions. It also casts between the types so you can also get a float value as an int. What it won't cast between is string or array/numeral types and it won't cast between string and array types.

**Comment by nesrak1** [comment]
I managed to get the Windows 7.1 sdk (the 2010 compiler) with http://stackoverflow.com/a/32322920
And Visual Studio 2010 with http://stackoverflow.com/a/3061839
Also sorry for not understanding, but I was wondering what the ClassDatabaseTypes were, in ->classes, I just see a list of things like "assign, at, back, begin" and am not really sure what that has to do with viewing the data.

**Comment by nesrak1** [comment]
Before I close this, what are the classIds supposed to be? I mean I see the list, and after a lot of trial and error I finally found the asset I wanted, but is there anyway I can selected the classId by it's path ID?
I thought it was the pathId, but I typed it in and it instead read "Unnamed asset", a MonoBehaviour.

**Comment by nesrak1** [comment]
So if I've got this right, ClassDatabaseType is the type of object like Gameobject or Script, and I have to look through the vector and pick the correct one I want to load, but then how am I supposed to be selecting asset ID 3?

```
int _tmain(int argc, _TCHAR* argv[])
{
	FILE *pFile = fopen("C:/Users/nesrak1/Documents/ModdingTest/Build/KnifeTest_Data/sharedassets0.assets", "rb");
	FILE *pClassFile = fopen("C:/Users/karse/Downloads/AssetsBundleExtractor_1.9_64bit/64bit/U5.3.1p3.dat", "rb");

	AssetTypeTemplateField* pBaseField = new AssetTypeTemplateField;
	ClassDatabaseFile* classDatabaseFile = new ClassDatabaseFile();
	classDatabaseFile->Read(AssetsReaderFromFile, (LPARAM)pClassFile);

	/*for(std::vector<ClassDatabaseType>::iterator it = classDatabaseFile->classes.begin(); it != classDatabaseFile->classes.end(); ++it) {
		std::wstring stemp = s2ws(it->name.GetString(classDatabaseFile));
		LPCWSTR result = stemp.c_str();
		MessageBox(0, L"Inside", result, MB_OK);
	}*/ //Same list as options -> edit type database

	pBaseField->FromClassDatabase(classDatabaseFile, &classDatabaseFile->classes[18], (DWORD)0); //18 should be material
	AssetTypeInstance ati = AssetTypeInstance(1, &pBaseField, AssetsReaderFromFile, (LPARAM)pFile, 0Ui64);
	const char *box = ati.GetBaseField()->Get(3)->GetName(); //I understand how like Get gets a child, but how do I select the material object in the first place? 
	std::cout << box << '\n';
	getchar();
	fclose(pFile);
	fclose(pClassFile);
	return 0;
}
```

**Comment by DerPopo** [comment]
Locate the entry in classDatabaseFile->classes using the classId. The classId is the type you can see on the right in hexadecimal when you have an asset selected in UABE. In the type database editor, it's called Type ID.
Using the index of the type database editor also works but the index likely isn't shared across all type databases.

Here's an example to get the name of an asset (if it has a m_Name field) :
'const char *box = ati.GetBaseField()->Get("m_Name")->GetValue()->AsString();'
Similarly, as you do in your code, you can use the child indices for Get (explicitly casting 0 to unsigned int/DWORD).
If it has no name field, ati.GetBaseField()->Get("m_Name")->IsDummy() == true.
In case it as no value (which would only be true if m_Name was no basic data type), GetValue would return NULL.

I'm not sure if VC 2010 fopen allows "/" instead of "\\" on Windows as the directory name separator, just in case it matters.

**Comment by nesrak1** [comment]
The part I was confused with was how to select the asset, but now I realize I needed to replace the last parameter of ati of the default 0Ui64 with assetsFileInfo->absolutePos.
And I did have what you put before, but I couldn't figure out how to change the read asset. Thanks for your help.

**Comment by nesrak1** [comment]
Now I can't figure out how to read the children of a gameobject through an array. Export dump shows:
```
0 GameObject Base
 0 vector m_Component
  0 Array Array (1 items)
   0 int size = 1
   [0]
    0 pair data
     0 int first = 4
     0 PPtr<Component> second
      0 int m_FileID = 0
      0 SInt64 m_PathID = 68239
 0 unsigned int m_Layer = 0
 1 string m_Name = "RainbowKnifeTest"
 0 UInt16 m_Tag = 0
 0 bool m_IsActive = true
```
I can `ati.GetBaseField()->Get("m_Component")->Get("Array")->GetValue()->AsArray()`
This returns a AssetTypeArray. So now what? How do I go on? I would like to get the PathID of the one and only component but the only thing there is `.size()`.
In the header, `//AssetTypeValueField *dataField;` is commented out. Maybe this hasn't been implemented into the API yet?

**Comment by DerPopo** [comment]
You can call Get on an array with the array index : Get("Array")->Get(0UL) for index 0 and so on. It should return a value field of "pair data" I think.

**Comment by nesrak1** [comment]
At first I just did `->Get("Array")->Get((unsigned int) 0)->Get("data")->Get("second")` instead of `->Get("Array")->Get((unsigned int) 0)->Get("second")`

**Comment by nesrak1** [comment]
Also how could I delete a whole asset? Both AssetsTable and AssetsFileTable don't seem to have any remove/delete function, and I can't find any list of any type anywhere.
