### ISSUE TITLE
Freezing / OBJ Texture messed up issue.

### ISSUE THREAD

**Issue by neoillusionkr** [DerPopo/UABE#59]
UABE 1.9 with 5.3 database.
I don't know exact Unity version of the game, I think it may be Unity 5.3, but not sure.

**Issue1. Some .unity3d file freeze the application while opening.**

When I open .unity3d file, application freezes.
After freeze, It leaks my memory.

Other files with this games, was successfully extracted.

Issued File : https://goo.gl/glL9rE

**Issue2. OBJ texture lines are messed up.**

When I export Mesh file with OBJ, some file has problem with mapping texture.
As you see, texture map has messed up, I can't see where did I have to place texture.

![2](https://cloud.githubusercontent.com/assets/8382794/17096838/46b085bc-5296-11e6-8a4e-dc601b9c0c9e.PNG)

As always, Thank you for your great work.

**Comment by DerPopo** [comment]
The .unity3d file has no visible file header, most likely the game applied custom compression/encryption.

The Mesh plugin does need some compatibility fixes. Could you tell me which Unity version the Mesh you mentioned belongs to (or send an example .assets/.unity3d file)?

**Comment by neoillusionkr** [comment]
Issued File : https://goo.gl/wqqkVA (Unity 5.x/Not sure with decimal version)

Not all Mesh has an issue.
For Example..

/BuildPlayer-WhiteDayEndingScene.sharedAssets/HanSoYoung : Abnormal (Messed-up)
/BuildPlayer-WhiteDayEndingScene.sharedAssets/ChoiEunMi_Ghost : Normal (No-issue)

Thanks for your help :)

**Comment by DerPopo** [comment]
I did some improvements to the Mesh plugin so your meshes should work in the next release, at least your example does. I hope these changes don't break other meshes though.

**Comment by DerPopo** [comment]
It should work now.

**Comment by neoillusionkr** [comment]
Thank you for your hard work.
Its working properly now. :)

Have a nice day.
