### ISSUE TITLE
Asset search

### ISSUE THREAD

**Issue by DerPopo** [DerPopo/UABE#6]
Add a search for assets by name or type and a goto file/path id.
Additionally add some sorting (maybe even a tree view sorted by the asset types?)

**Comment by 0x900x90** [comment]
Maybe you will find ideas in this two assets apps. They have batch, sort and search functionality, but working unstable.

http://www.zoneofgames.ru/forum/index.php?showtopic=36240&st=0&start=0
download link
https://yadi.sk/d/m3vFWoQ3j62Cr

http://www.zoneofgames.ru/forum/index.php?showtopic=27641&st=180
download link
https://www.dropbox.com/s/2qorsfd50ixvn6o/UnityAssetsExplorer.exe

**Comment by DerPopo** [comment]
Added sorting, search and go to asset functionality. It uses more memory now (multi-column Win32 list view vs. Win32 list box) but it isn't too bad (100 MiBs for opening 7dtd's mainData with all dependencies still is much less than the game uses itself).
