### ISSUE TITLE
Problem reading 5.3.4p6 file

### ISSUE THREAD

**Issue by santaslilhelper** [DerPopo/UABE#61]
I tried any number of ways to read this file but I keep getting an error telling me the file is compressed.  When I say "yes" to uncompressing the file it says "Unable to decompress the bundle file!"

Here is the file in question: https://drive.google.com/file/d/0B5WUIlsciwhBNXhvekJQYmlyT2c/view

**Comment by santaslilhelper** [comment]
Also a little more information.

These files are located in a `data/files/UnityCache/Shared/<hash>` folder.  It is a `__data` file and also contains an `__info` file with it.  The info files don't contain much. here is the one for the above.

```
-1
1470160479
1
__data
```
And I am guessing you know this but these files are streamed to client after the initial game startup.

Thanks again

**Comment by DerPopo** [comment]
Fixed two things for the next release so such files can also be decompressed properly.
The first bug caused decompressing bundles with compressed blocks but no compressed file table to fail, the second one caused issues with bundle files that have their file table at the end (after the included files).

**Comment by scoot1585** [comment]
awesome, thanks for looking into it! when do you think the next release will be?

**Comment by santaslilhelper** [comment]
Awesome, any idea when the next release is?  There is about 2000 files I wanted to decompress for information website about the game.  Thanks again!

**Comment by santaslilhelper** [comment]
@DerPopo I looked around and saw this issue https://github.com/DerPopo/UABE/issues/55 where you said hopefully a new release will be out in 2-3 weeks as long as there were no major bugs.  Is that still the plan to release soon?  And I am hoping this includes API updates?

Again, thanks for the help, I'd buy ya a beer if I could for the release :)

**Comment by DerPopo** [comment]
I'm still trying to get it released as soon as possible. There will also be a new API release with a Write function for bundles.
There is a command line batch-export for the .assets files inside multiple bundles (haven't tested it for compressed files) but you'd still have to manually export all textures of each of the 2000 files. I'll see if I can add a batch view for .assets files.

**Comment by santaslilhelper** [comment]
sounds great, and that would be awesome for the batch view. 

i'll keep watching for the release, goodluck!

**Comment by DerPopo** [comment]
As more and more improvements found their way into the code, it took a bit longer than expected but it's out now.

**Comment by santaslilhelper** [comment]
Thank you again!  Textures are exporting now.  I'll file new tickets if I find anything new.

Again thanks for all your hard work :)
