### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by theonlyShiro** [DerPopo/UABE#65]
Can you add this tool the type database 5.4.3.1p3 that faeria uses? @DerPopo

**Comment by DerPopo** [comment]
The type databases in 2.0 will be 3.4.0f5, 3.5.0f5, 4.0.0f7, 4.1.5f1, 4.2.2f1, 4.3.4f1, 4.5.4f1, 4.6.4f1, 4.7.2f1, 5.0.1f1, 5.1.1p3, 5.2.0f3, 5.3.1p3, 5.4.0f3.

**Comment by blackwhattack** [comment]
That's great!
When do you think you would be able to publish 2.0?

**Comment by DerPopo** [comment]
It's out now.
