### ISSUE TITLE
Batch request for unity3d files.

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#66]
Web builds sometimes contain to much files for exporting them manually. Batch processing would be nice.

**Comment by DerPopo** [comment]
The command line can be used for batch exporting/importing of bundles. Usage.txt should cover it.
2.0 also fixes issues with compressed files.

**Comment by 0x900x90** [comment]
Ok. Understood now how the batch works.

Too bad UABE is not working on XP again. I fixed 1.9 myself by replacing SetThreadErrorMode to SetErrorMode. But 2.0 can't open file. Error: "Unable to open the file in read mode!". Something changed in file opening routine?

**Comment by 0x900x90** [comment]
Ok. Understood now how the batch works.

Too bad UABE is not working on XP again. I fixed 1.9 myself by replacing SetThreadErrorMode to SetErrorMode. But 2.0 can't open file. Error: "Unable to open the file in read mode!". Something changed in file opening routine?

P.S. I know you recommend to upgrade OS.

**Comment by DerPopo** [comment]
I did change the file opening to support multiple files but I also have added one the GetOpenFileName fallback. Just tried it, and there is indeed a problem when opening a single file. Opening multiple files seems to work. I'll look into it.

**Comment by DerPopo** [comment]
Should be fixed now :
[AssetsBundleExtractor_2.0b_XPFix.zip](https://github.com/DerPopo/UABE/files/436783/AssetsBundleExtractor_2.0b_XPFix.zip)

**Comment by 0x900x90** [comment]
It works! Thank you!
