### ISSUE TITLE
Batch request not working (" I am too old")

### ISSUE THREAD

**Issue by guile2912** [DerPopo/UABE#68]
Hello,
I can open an asset archive ( version 5.3.5f1 ) manualy using the programm, it works fine.
But when I try do do it with a batch text file, and using the command line, it says it cannot open it because it may be too old.
How is  it working manually but not in batch mode ?

Thank you very much for your work !

**Comment by DerPopo** [comment]
I haven't tested the batch part for a while now. While it shares a lot of code with the user interface, there are some parts specific to batch support that may be broken.

**Comment by guile2912** [comment]
Thanks for your fast answer :)
Do you think you will have time to make it work in the next release ?
Thanks again.

**Comment by DerPopo** [comment]
It should work now. Please report back if this issue can be closed, or if there are more issues.
