### ISSUE TITLE
Incorrect .obj export

### ISSUE THREAD

**Issue by aspadm** [DerPopo/UABE#69]
I test .obj export using last version tool. Game DeusEx:GO.

First, when I try export two files, plugin just throw 2 errors.

Second, when I select only one file for export, plugin give me .obj file with incorrect vt(texture coords?) and polygons. Vertixes and half of polygons looks good.

There is some first strings of output .obj file:

# Mesh "Jensen_Skin" exported with Unity Assets Bundle Extractor; 12609 vertices, 20775 indices, 24 bytes per vertex
g Jensen_Skin
# SubMesh 0
# Vertices
v 0.184241 1.497549 -0.042167
vt 0.000000 -170141183460469230000000000000000000000.000000
vn 0.430840 0.787622 0.440486
v 0.161888 1.461562 0.042615
vt 3.243572 -170141183460469230000000000000000000000.000000
vn 0.233122 0.836236 0.496350

Sorry for my bad english.

**Comment by DerPopo** [comment]
Could you test it again with 2.0?

**Comment by aspadm** [comment]
New version working well
