### ISSUE TITLE
Unable to export sound and .resource file

### ISSUE THREAD

**Issue by catxsuika** [DerPopo/UABE#70]
First I'll thank author for this useful tool.

The problem is that I can't extract wav files with AudioClip plugin which is similar to issue #44. 
![5](https://cloud.githubusercontent.com/assets/21059890/17883259/8a67300e-694c-11e6-832c-2df181d065ad.PNG)

I've tried the temporary workaround but unfortunately it didn't work.
I tried to export .resource file but when I pressed Export, the file size remains 0kb with memory increasing .
![1](https://cloud.githubusercontent.com/assets/21059890/17883340/f33619ec-694c-11e6-950f-16809da18cb5.PNG)
![2](https://cloud.githubusercontent.com/assets/21059890/17883346/f85f9bf0-694c-11e6-8869-0c5c7f8f0cd8.PNG)
![3](https://cloud.githubusercontent.com/assets/21059890/17883350/fbc4868e-694c-11e6-9f88-81326c0e67a9.PNG)
I press the buttons again after a long time, but it still said "A file operation is still running".
![4](https://cloud.githubusercontent.com/assets/21059890/17883354/04728362-694d-11e6-8af2-c21544349b68.PNG)

Here's the file: https://www.dropbox.com/s/mte0mxg73w2n37i/bgm-bgm_001_2cdcbc3c58497a288c05f33b9636f207?dl=0 
It's from a game on WebGL platform.
As I know, the audio in WebGL is done differently then on all other platforms, which means it's not using FMOD. I don't know if it's supported in UABE.

What can I do?
@DerPopo

**Comment by DerPopo** [comment]
Both things should be fixed now. 2.0 exports the .m4a files from WebGL builds.

**Comment by catxsuika** [comment]
Yes, it works now :) Thanks for all your hard work
