### ISSUE TITLE
Crash when you open info of uncompressed asset bundle

### ISSUE THREAD

**Issue by Skippeh** [DerPopo/UABE#71]
The program crashes when you decompress an asset bundle file and try to view the info of the non resource file. Same happens if you export first and open it directly.

Not sure what unity version it's built with but the game is Rust. Happens with any bundle file.

This did not happen in version 1.9.

**Comment by DerPopo** [comment]
Does 2.0b fix it?

**Comment by Skippeh** [comment]
Yes, it works now.

Good job! :+1:
