### ISSUE TITLE
API 2.0 defines.h missing includes and ClassDatabaseFile.Write is missing in dll

### ISSUE THREAD

**Issue by nesrak1** [DerPopo/UABE#72]
The defines.h file does not have any includes, so it errors on everything.
```
#include "stdafx.h"
#include <string>
#include <iostream>
#include <Windows.h>
#include <fstream>
```
is a fix.

Also attempting to use ClassDatabaseFile.Write causes runtime error:
`The procedure entry point ?Write@ClassDatabaseFile@@QAE_KP6A_K_K0PBXJ@ZJ0HK_N@Z could not be located in the dynamic link library C:\Users\nesrak1\documents\visual studio 2010\Projects\SubModderCPPBridge\Release\SubModderCPPBridge.exe. `

Except for the fact that if I look at the dll, it specifically says that there is a function called `?Write@ClassDatabaseFile@@QAE_KP6A_K_K0PBXJ@ZJ0HK_N@Z`

It's only that one though, all of the other API functions are working fine.

**Comment by DerPopo** [comment]
I couldn't find out why it can't find the ClassDatabaseFile::Write method as it has the same decorated name in both the lib and the dll. I've recompiled it with the includes in defines.h in case it helps.

**Comment by nesrak1** [comment]
Turns out forgot to delete the dll and lib inside the Release folder, and I had only deleted the ones out of the Debug folder.
