### ISSUE TITLE
Cannot add/remove asset with large size

### ISSUE THREAD

**Issue by nesrak1** [DerPopo/UABE#74]
If an assets file contains a large PathID it freezes UABE when trying to add or remove an asset. Deleteing the asset fixes the bug.

**Comment by nesrak1** [comment]
Actually, most assets files in other games _do_ contain path 4800000, but it's only this one specific assets file that crashes UABE trying to add and remove and removing this asset _does_ fix it. It takes around about ~20 seconds to delete this path 4800000 file... then after that it takes 1 second to delete/add anything else.

**Comment by nesrak1** [comment]
Turns out everything else deletes in about 50 seconds each, while that specific asset took about 14.
So large files take forever to delete and the add dialog takes just as long to open.

**Comment by nesrak1** [comment]
Anyway, how could I delete an asset in the API?

**Comment by DerPopo** [comment]
Put an asset remover (AssetsReplacer.h) into the replacers list for the AssetsFile::Write function.

**Comment by nesrak1** [comment]
I'm guessing monoScriptIndex is the ID of the type value that monobehaviours use if I delete a monobehaviour? If so how can I tell what this is?

**Comment by DerPopo** [comment]
classID and monoScriptIndex aren't used for removers, so you don't have to set it. monoScriptIndex is the same as inheritedUnityClass in AssetFileInfo.

**Comment by nesrak1** [comment]
One more thing, how could I loop through all of the assets? I'm using a for loop with .getAssetInfo() but if that ID is skipped (56, 57, 59) then it errors.

**Comment by DerPopo** [comment]
The array pAssetFileInfo/assetFileInfoCount itself is public, so you could loop through it.

**Comment by nesrak1** [comment]
I know there are exactly 5 monobehaviours (so monoCount = 5)
```
AssetsReplacer **replacors = new AssetsReplacer*[monoCount];
	int ad = 0;
	for (int i = 1; (unsigned int)i < assetsFileTable.assetFileInfoCount; i++) {
		AssetFileInfoEx* assetsFileInfo = assetsFileTable.getAssetInfo(i);
		if (findAssetClassByName(classDatabaseFile, assetsFileInfo) == "MonoBehaviour") {
			assetDeleter = MakeAssetRemover(0, assetsFileInfo->index, assetsFileInfo->curFileType, assetsFileInfo->inheritedUnityClass);
			replacors[ad] = assetDeleter;
			ad++;
		}
	}
	std::cout << "Done";
	assetsFile.Write(AssetsWriterToFile, (LPARAM)pOutputFile, 0, replacors, monoCount, 0);
	fclose(pOutputFile);
```
Hopefully I did arrays correctly, I've never used arrays in c++...

It stops at assetsFile.Write, but points toward ostream

**Comment by DerPopo** [comment]
Use the array like this :
```
	for (unsigned int i = 0; i < assetsFileTable.assetFileInfoCount; i++) {
		AssetFileInfoEx* assetsFileInfo = &assetsFileTable.pAssetFileInfo[i];
```
Just to be sure : If findAssetClassByName returns a std::string, the == can be used on it but if it returns a normal c string (char*), the names should be compared with e.g.
`if (!strcmp(findAssetClassByName(...), "MonoBehaviour"))`

**Comment by nesrak1** [comment]
Stopping at same place, but now erroring at atonexit.c

**Comment by nesrak1** [comment]
As a test I did just this and it still errors at atonexit.c

```
	FILE *pFile = fopen(inputAssets.c_str(), "rb");
	FILE *pClassFile = fopen(inputClasses.c_str(), "rb");
	FILE *pOutputFile = fopen(("noscript_" + inputClasses).c_str(), "wb");

	AssetsFile assetsFile(AssetsReaderFromFile, (LPARAM) pFile);
	AssetsFileTable assetsFileTable(&assetsFile);

	AssetsReplacer **replacors2 = new AssetsReplacer*[1];
	AssetFileInfoEx* assetsFileInfo = assetsFileTable.getAssetInfo(71929); //last mono in file
	replacors2[0] = MakeAssetRemover(0, assetsFileInfo->index, 0);
	assetsFile.Write(AssetsWriterToFile, (LPARAM)pOutputFile, 0, replacors2, 1, 0);
	fclose(pOutputFile);
```

**Comment by nesrak1** [comment]
So is it anything I'm doing wrong?

**Comment by DerPopo** [comment]
I can't reproduce the issue, the same code works for me with changed file paths.
Could you try just calling AssetsWriterToFile with pos 0, size 1, data as a pointer to any byte, and (LPARAM)pOutputFile and see if it crashes?

**Comment by nesrak1** [comment]
It had nothing to do with any of that code at all. inputclasses was returning the whole path instead of just the file name ...

**Comment by nesrak1** [comment]
One more thing, how could I edit one of the values? I'm assuming I'm going to have to use AssetsReplacer?

**Comment by nesrak1** [comment]
Bumpity bump bump?

**Comment by DerPopo** [comment]
You likely want MakeAssetModifierFromMemory, with fileID/pathID as usual, classID (== curFileType in AssetFileInfo), monoScriptIndex (== scriptIndex in AssetFileInfo), your buffer and size, and an optional callback to free the buffer when the modifier gets freed (e.g. `void FreeMyBuffer(void *buffer){free(buffer);}`).
If you have a template field for the type you are looking for, you can use AssetTypeInstance/AssetTypeClass for it. Commit the changes to the fields, call AssetTypeClass::Write. For writer/writerPar you can use AssetsWriterToMemory/Create_AssetsWriterToMemoryDynamic(). Once it's written, you can call Get_AssetsWriterToMemory_Buf with a pointer to a size variable (you can leave pPos NULL) to get the wanted buffer, Free_AssetsWriterToMemory with freeIfDynamic = false and create the AssetModifierFromMemory with Free_AssetsWriterToMemory_DynMem as the callback.

In case the .assets file you are editing is in a bundle, you can use this to get the type template :
```
AssetTypeTemplateField myTypeTemplate;
bool templateRead = false; //just indicates failure/success
if (pAssetsFile->header.format >= 0x0D) //Unity 5.x+
{
	for (DWORD i = 0; i < pAssetsFile->typeTree.fieldCount; i++)
	{
		if (pAssetsFile->typeTree.pTypes_Unity5[i].classId == <searched class id>)
		{
			templateRead = myTypeTemplate.From0D(&pAssetsFile->typeTree.pTypes_Unity5[i], 0);
			break;
		}
	}
}
else if (pAssetsFile->header.format >= 0x07) //Unity 3.5 - 4.x
{
	for (DWORD i = 0; i < pAssetsFile->typeTree.fieldCount; i++)
	{
		if (pAssetsFile->typeTree.pTypes_Unity4[i].classId == <searched class id>)
		{
			templateRead = myTypeTemplate.From07(&pAssetsFile->typeTree.pTypes_Unity4[i].base);
			break;
		}
	}
}
```
If it isn't and it's a MonoBehaviour, you'd have do it the usual way of finding out the fields with a decompiler and putting it into a custom type database.

**Comment by nesrak1** [comment]
Reopening this because I still can't add anything in the UI when Unity exports PathIDs with 80000000+

**Comment by DerPopo** [comment]
It seems like updating each asset list entry's item pointer caused an update of the selected asset information shown right because each item update causes a list change event. I've simply added a check so it doesn't update the selection in that case and adding/removing assets works much faster now.
I've also simplified the path id suggestion in the add dialog so it just searches for the highest id.
