### ISSUE TITLE
Code/Documentation Help

### ISSUE THREAD

**Issue by NPBruce** [DerPopo/UABE#75]
Sorry this is not an issue, but I could not find another way to contact anyone involved with this project.

I am working on a open replacement for a board game helper app (see: https://github.com/NPBruce/valkyrie).  Currently I have manually extracted some assets from the official app (thanks for your tool!).  I would however like to automatically pull this data out of the app at run time to avoid legal issues.

So I would like to dig into the assets programatically.  I see you have an API, however the creative commons licence makes it a little unclear to me if I could incorporate this and it is not platform independent as my solution needs to exist within the mono runtime.

So it would be great if I could either see some sample code for how you are getting to the asset data, or at least point me in the direction of how you worked this information out.

Thanks,
Nathan Parslow.

**Comment by DerPopo** [comment]
If you use the API, you don't have to put your own code under any specific license. A small note of using it would already be enough, if appropriate.
The AssetsFileFormat and AssetsBundleFileFormat headers contain the structs of the file formats (AssetsList only has count and the entries, the other structs should be identical).
The asset types' structure is inside the TypeTree in case of bundles, else the player directly reads it. The type database package in UABE contains full type information for each Unity build it has, which you can view through the type database editor (after extracting one version from the package editor).
RaduMC's UnityStudio is written in C# in case it helps.

**Comment by NPBruce** [comment]
Thanks very much this is useful information, I will see what I can get working.
