### ISSUE TITLE
[Question] Raw filesystem assets (streaming assets) support

### ISSUE THREAD

**Issue by jorgerobles** [DerPopo/UABE#76]
Hi!

Does/Will the application have support for Filesystem Streaming Assets?
https://docs.unity3d.com/Manual/StreamingAssets.html

I've found that some assets are not compressed on AssetBundle files, but layered out on filesystem. (Seems platform dependant: On Android seems to be a Jar file, on IOS on Raw folder). 
These files are listed on a contentinfo.txt file, but cannot open them (File not recognized).Headers contain UnityFS comments opening on raw hex editor.

Thanks!

**Comment by DerPopo** [comment]
Android's apk files are like .zip files, you can open them with 7-Zip (maybe it also works with Windows' explorer when renaming the extension). I don't know about iOS files but they usually contain .assets files that can be opened inside UABE.

**Comment by jorgerobles** [comment]
Thanks but seems I'm slipping something, I sent you a PM  on 7daystodie forum.
