### ISSUE TITLE
Export Sound: Unable to open the streamed data file!

### ISSUE THREAD

**Issue by SvardXI** [DerPopo/UABE#78]
An issue with Ori and the Blind Forest assets where any attempt to use the Export Sound plugin returns the following error:

Unable to open the streamed data file!

Unfortunately, I can not seem to figure out the exact version number of Unity it uses. Exporting texture and Mesh files works fine, and I can view and export data for most files in the game. It's just the AudioClips that seem to give me issues thus far. Let me know if there's any other information you might need, or if you need a *.asset or *.resource file.

**Comment by DerPopo** [comment]
Can you upload the smallest .assets file that also has a .resource file next to it?
