### ISSUE TITLE
Compressed shaders.

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#79]
Do you have any info about compression? Unity player decompresses shader before sending it to VGA adapter or sends it compressed? I just want to find compression algo. Can we use "D3DDecompressShaders" from d3dcompiler_46.dll? Please share information, if you have.

BTW. Compression looks strange, because there are too much null bytes.

Looks like shader data block compressed using lz4 algo. Am i right?

**Comment by DerPopo** [comment]
I don't really know what format the files are saved as. Maybe it's a higher-level equivalent of Vulkan's SPIR-V, some sort of intermediate binary language.
I'm not sure if it's LZ4. LZ4 doesn't touch data it can't compress (or which isn't in the file before) but I don't think it would leave that many null bytes.

**Comment by 0x900x90** [comment]
It does. I tried to compress jpg file with lz4 utility. I got many null bytes inside.

Here is how it looks.
http://s21.postimg.org/jp4cww993/Clipboard.jpg

Compressed data looks similar with shader data.

I will continue experiments with this.

**Comment by 0x900x90** [comment]
My guess is right. Shaders data compressed using lz4 algo. But when i decompressed it, i got nothing interesting. It is still binary data.
