### ISSUE TITLE
Audio extraction problem

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#80]
Sometimes path to external resource looks like this and it's impossible to extract it.
http://s9.postimg.org/qrs00qkz3/112.jpg

**Comment by DerPopo** [comment]
Is the asset in a bundle?

**Comment by 0x900x90** [comment]
It worked, when i unpacked bundle, pressed info button and tried to extract.

Before this i exported "BuildPlayer-AlpineLodge.sharedAssets" and "BuildPlayer-AlpineLodge.resource" into the same folder. Got error described in 1st message.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out. Feel free to open a new issue if you have further questions.
