### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Kurainu** [DerPopo/UABE#81]
I would like when your awesome tool kit can extract the **sprites** of the assets files.

**Comment by DerPopo** [comment]
The sprite textures can already be extracted. There should be  PPtr<Texture2D> texture inside SpriteRenderData if you press View Data. Expand texture and you can see the file id inside brackets and the path id, which you can use to find the texture in the list.

**Comment by theonlyShiro** [comment]
@DerPopo Is it possibly to extract the meshes with the material/UV already set that i only have to set the texture path. That would be so awesome.
