### ISSUE TITLE
Export Dump Bug

### ISSUE THREAD

**Issue by tank33** [DerPopo/UABE#84]
Can't export dump MonoBehaviour, gets "ERROR The file format is empty".

**Comment by DerPopo** [comment]
I'll fix it, but it isn't of big use anyway as it only knows the static fields, not the fields added by the game (which are the interesting ones).

**Comment by VivekDeshpande** [comment]
I'd like this too

**Comment by DerPopo** [comment]
MonoBehaviour export will be supported in the next release.
