### ISSUE TITLE
Cannot export the correct index buffer for the mesh which has more then 1 submesh.

### ISSUE THREAD

**Issue by codewings** [DerPopo/UABE#85]
Hi, I am now trying to use 2.0b to export the mesh data of a game made with unity. I found that the obj plugin only export one mesh even it has more than one mesh. And the index buffer it exported is incorrect.

**Comment by codewings** [comment]
About the incorrect index buffer, I found that when I imported the file into blender, it is perfectly displayed. But the mesh is still a whole mesh instead of compositing by 2 sub-meshes.

**Comment by nesrak1** [comment]
I think if you open up the obj file in a text editor it is already separated by sub meshes and you can just manually cut one part in paste it into another file. I think I have a blender script that does this automatically.
