### ISSUE TITLE
Searching assets in the API

### ISSUE THREAD

**Issue by nesrak1** [DerPopo/UABE#86]
I know a for loop searching through an assets file of 500,000 assets long is going to be extremely slow for just names, so is there any easier way that I can search for names of assets? Maybe a table with the asset names and nothing else?

**Comment by DerPopo** [comment]
The ResourceManager asset in mainData/globalGameManagers or the AssetBundle asset in a bundle contains the path of all assets that have a path. If the asset you are looking for has a path, it's definitely the fastest way to deserialize the ResourceManager/AssetBundle asset through AssetTypeInstance and search for the path to find out the file/path id (the file id is either 0 for the current .assets file or any 1-based index into the .assets' dependency table). If it hasn't got a path, the only direct way to find an asset by its name is by looking for the m_Name field in every single asset.
In some cases, the asset might be referenced to by another asset which does have a path (e.g. the GameObject of a Transform, a parent GameObject that is linked through the Transform or any other link).

**Comment by nesrak1** [comment]
But how do I search in the first place? SearchChild? Loop through them all?
I can't do either because when I try to load the AssetTypeInstance it freezes.

**Comment by nesrak1** [comment]
Would ResourceManager tell me what filename goes to what fileid? I thought maybe it would be in dependencies but I see 8 in UABE and only 4 in code

**Comment by DerPopo** [comment]
AssetsFile::dependencies contains all direct references, fileid 1 is the first dependency (index 0) and so on.
UABE also resolves dependencies of dependencies but that's not necessary to find referenced assets.

You can use the ResourceManagerFile class (ResourceManagerFile.h) and its Read function (forgot to mention that), the containerArray (with containerArrayLen items) has all the path names and asset references that are available.

**Comment by nesrak1** [comment]
Once again it's me being dumb and using comparing the wrong assets file, they both have 4 now.

About the ResourceManagerFile, I don't know how to actually load a file. There's no LPARAM for it.

**Comment by nesrak1** [comment]
What are the parameters for ResourceManagerFile then? Specifically filePos and bigEndian (is this false?)

**Comment by DerPopo** [comment]
The parameters for Read are : void *data, int dataLen (pass a pointer to and the length of the ResourceManager asset data in memory), int *filePos (pass a pointer to an int initialized to 0), int assetsVersion (AssetsFile::header.format), bool bigEndian (AssetsFile::header.endianness).

**Comment by nesrak1** [comment]
So data is the AssetsFile?

**Comment by DerPopo** [comment]
data should be the pointer to the ResourceManager asset in memory (look for type 0x93 in the AssetsFileTable).
You could alternatively pass a pointer to the mainData/globalgamemanagers file in memory and initialize the filePos int to the AssetsFileTable's absoluteOffset instead.

**Comment by nesrak1** [comment]
Am I doing this correctly?
Error on read()
Sorry for not understanding
```
	AssetsFile assetsFile(AssetsReaderFromFile, (LPARAM) pFile);
	AssetsFile assetsFileGGM(AssetsReaderFromFile, (LPARAM) pFileGGM);
	AssetsFileTable assetsFileTable(&assetsFile);
	AssetsFileTable assetsFileTableGGM(&assetsFileGGM);	

	AssetTypeTemplateField* pBaseField = new AssetTypeTemplateField;
	ClassDatabaseFile* classDatabaseFile = new ClassDatabaseFile();
	classDatabaseFile->Read(AssetsReaderFromFile, (LPARAM)pClassFile);

	AssetFileInfoEx* assetsFileInfo = assetsFileTable.getAssetInfo(stoi(str));
	AssetFileInfoEx* assetsFileInfoGGM = assetsFileTableGGM.getAssetInfo(13);
	ResourceManagerFile* resourceManager = new ResourceManagerFile();
	resourceManager->Read(assetsFileInfoGGM, assetsFileInfoGGM->GetSize(assetsFileGGM.header.format), (int*)assetsFileInfoGGM->absolutePos/*0*/, assetsFileGGM.header.format, assetsFileGGM.header.endianness);
	
	for (int i = 0; i < resourceManager->containerArrayLen; i++) {
		std::cout << resourceManager->containerArray[i].name;
	}
```

**Comment by DerPopo** [comment]
The ResourceManagerFile::Read function requires a memory buffer to the ResourceManager asset and its size. If you read the whole .assets file into memory, you'd need to initialize an int value (similarly to tmpAssetPos below but not with 0) with absolutePos but I recommend the way it's done below. 
The static AssetFileInfo::GetSize function doesn't return the size of the asset but the size of the asset list entry in the .assets file (which a tool using the API usually doesn't need). Use the curFileSize field instead.
```
	<snip>
	AssetFileInfoEx* assetsFileInfo = assetsFileTable.getAssetInfo(stoi(str));
	AssetFileInfoEx* assetsFileInfoGGM = assetsFileTableGGM.getAssetInfo(13);
	char *resourceFileBuf = new char[assetsFileInfoGGM->curFileSize]; //ideally initialize the buffer to 0s or check the returned read size from AssetsReaderFromFile below
	//could also use fseek/fsetpos + fread but it's easier like this :
	AssetsReaderFromFile(assetsFileInfoGGM->absolutePos, assetsFileInfoGGM->curFileSize, resourceFileBuf, (LPARAM)pFileGGM);
	ResourceManagerFile* resourceManager = new ResourceManagerFile();
	int tmpAssetPos = 0;
	resourceManager->Read(resourceFileBuf, assetsFileInfoGGM->curFileSize, &tmpAssetPos, assetsFileGGM.header.format, assetsFileGGM.header.endianness);
	delete[] resourceFileBuf;
	<snip>
```
Btw, I recommend explicitly setting the readNames parameter to false unless it's really needed, e.g. AssetsFileTable assetsFileTable(&assetsFile, false);
Otherwise, it reads the m_Name field of every single asset that has one and it requires quite some random access on disk depending on the asset count in the .assets file.

**Comment by nesrak1** [comment]
Yes it works now thanks

**Comment by nesrak1** [comment]
I was trying to get the name and tag/layer of an asset(gameobject) by it's ID in a file, and for some strange reason it kept stopping on assettypeinstance. (Access violation reading location 0x00000004) I then tried to use the printChildNameByID test I made a while back (which has always worked) until just now. I'm also sure it is not the class files as I tried 3 different versions.

After the 2.0 update I guess I just never used class files at all.
Here is the code:
```
std::string printChildNameByID(int ID, std::string inputAssets, std::string inputClasses) {
	std::cout << "SUBMODDERCPPBRIDGE\\CalledCommand> printChildNameByID(" << std::to_string((long double) ID) << ", " << inputAssets << ", " << inputClasses << ")\n";
	//File loading
	FILE *pFile = fopen(inputAssets.c_str(), "rb");
	FILE *pClassFile = fopen(inputClasses.c_str(), "rb");
	
	//Picked asset
	AssetsFile assetsFile(AssetsReaderFromFile, (LPARAM) pFile);
	AssetsFileTable assetsFileTable(&assetsFile);
	AssetFileInfoEx* assetsFileInfo = assetsFileTable.getAssetInfo(ID);

	//Classes
	AssetTypeTemplateField* pBaseField = new AssetTypeTemplateField;
	ClassDatabaseFile* classDatabaseFile = new ClassDatabaseFile();
	classDatabaseFile->Read(AssetsReaderFromFile, (LPARAM)pClassFile);

	pBaseField->FromClassDatabase(classDatabaseFile, &classDatabaseFile->classes[findAssetClass(classDatabaseFile, assetsFileInfo)], (DWORD)0);
	AssetTypeInstance ati = AssetTypeInstance(1, &pBaseField, AssetsReaderFromFile, (LPARAM)pFile, assetsFileInfo->absolutePos);
	const char *output = ati.GetBaseField()->Get("m_Name")->GetValue()->AsString();
	return std::string(output);
}
```
