### ISSUE TITLE
ETC_RGB4 Textures not exporting to png correctly

### ISSUE THREAD

**Issue by mcorner** [DerPopo/UABE#88]
I am attempting to export textures that are in the ETC_RGB4 format to png.  The pngs are coming out in a very strange tiling pattern.

Sample export attached:
![alpha](https://cloud.githubusercontent.com/assets/316076/21061944/9b99e978-be1c-11e6-8614-038bad862966.png)

Sample asset file attached:
[sharedassets4.assets.zip](https://github.com/DerPopo/UABE/files/643011/sharedassets4.assets.zip)

**Comment by 0x900x90** [comment]
Looks like it originally saved like this.
