### ISSUE TITLE
I can't open .assets.resS file

### ISSUE THREAD

**Issue by windmillknight** [DerPopo/UABE#89]
I can't open a  sharedasset.assets.resS file using UABE v2.0. Why? 
![16n8 az j3 y 94wq_knat](https://cloud.githubusercontent.com/assets/18244752/21090079/4078676e-c078-11e6-93fa-83f93ab31907.png)
![d x32ibip cp1gmfb6lh5u4](https://cloud.githubusercontent.com/assets/18244752/21090080/40f4fc34-c078-11e6-89db-0f2fea60928c.png)

**Comment by nesrak1** [comment]
That's just raw file data for textures and sound... if you want to extract just open up the regular assets file.
Also if you view data on a texture or sound I think you can find the exact position and length in the resS.
