### ISSUE TITLE
Cannot properly read assets with external ".resource" file in a bundle

### ISSUE THREAD

**Issue by jack980517** [DerPopo/UABE#91]
I have an asset bundle that contains an assets file and a ".resource" file. UABE can only see the info/metadata, but not the audio file itself (which is in the ".resource" file). Selecting "CAB-xxx.resource" in the drop-down menu would cause the program to say that it's not a valid assets file. 

The file in question has been uploaded here:
https://mega.nz/#!skJW0IrR!1901uAG4fhLvxvwMCP3-8L--Rw6VokM7A0zy4tWXbI0

**Comment by DerPopo** [comment]
The .resource file contains only raw data that is used by the .assets file.
The AudioClip plugin can extract the data if you select the AudioClip in the .assets file.

**Comment by jack980517** [comment]
But what about importing? Can it be supported? I need importing more, and extracting is already supported by other applications like Unity Studio...

**Comment by DerPopo** [comment]
It can be done manually as described in this old post : https://7daystodie.com/forums/showthread.php?32600-Overriding-vanilla-files-(assets-)&p=314195&viewfull=1#post314195
The m_Source has a special format in bundles, just take a look at the original AudioClip's m_Source.
I'll of course see what I can do to create FMOD sound banks in the same way as Unity.

**Comment by jack980517** [comment]
Thanks. So just to confirm, I need to build my own AssetBundle, switch the .resource file and edit the .assets file to match?
I tried replacing the whole AssetBundle (i.e. .assets + .resources) but the game refused to recognize it. Didn't think of only replacing .resource though.

**Comment by jack980517** [comment]
Just tried and succeeded. Thanks a lot!

**Comment by RingyRing** [comment]
> It can be done manually as described in this old post : https://7daystodie.com/forums/showthread.php?32600-Overriding-vanilla-files-(assets-)&p=314195&viewfull=1#post314195 The m_Source has a special format in bundles, just take a look at the original AudioClip's m_Source. I'll of course see what I can do to create FMOD sound banks in the same way as Unity does.

Sorry for bumping an old thread. The page with the linked post has been deleted. I tried looking for the archived version of the page, but it has never even been archived. Can you please explain how to edit such audio files here again?

**Comment by RingyRing** [comment]
Thanks!

**Comment by SeriousCache** [comment]
@RingyRing UABE 3.0 also can import resources through View Data - right click on the resource field. 
To copy an AudioClip asset, you would essentially transfer all the regular values such as m_Length (manually or via Export Dump/Import Dump) and then transfer the resource (View Data on the original asset and export the resource, View Data on the new asset to import the data).  
Also, mod installers now support resource changes.

**Comment by RingyRing** [comment]
@SeriousCache How do I edit the exported resource file?

**Comment by RingyRing** [comment]
@SeriousCache If I use your new method, how will the steps in @jack980517 's instructions change?
