### ISSUE TITLE
Feature request: Dumping to and importing from JSON

### ISSUE THREAD

**Issue by jack980517** [DerPopo/UABE#92]
For some asset types (e.g. MonoBehaviour), the current "Import dump" and "Export dump" buttons works with a plain text file format. If this format is changed to JSON, it would be easier for other programs to process the data.

**Comment by DerPopo** [comment]
It didn't make it to 2.1 but it's planned for the next release.

**Comment by luckcolors** [comment]
Any status update on this?

**Comment by luckcolors** [comment]
Like it should be staright forward for you to add if you already get everything into an object.
usually json libs just require a function call to get out json out of an object.

**Comment by DerPopo** [comment]
Implemented simple JSON dump export, still need to do import.

**Comment by luckcolors** [comment]
Thanks man. As long as it has the same info as the txt tree it will be ok. Let me know when you publish the update.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out.

**Comment by luckcolors** [comment]
Cool thanks :)
