### ISSUE TITLE
Use UABE in android unity game

### ISSUE THREAD

**Issue by kelalung** [DerPopo/UABE#93]
I edit a texture2d in mainData which has 2300 file (name with 32 character). The uabe show message error
Anyway, can i edit it and save file mainData?

I use uabe version 2B
![untitled](https://cloud.githubusercontent.com/assets/1118901/21426736/34a62210-c883-11e6-8f6b-35fdf9215de8.png)
![untitled1](https://cloud.githubusercontent.com/assets/1118901/21426737/34a9e3d2-c883-11e6-8832-156bce54bd71.png)

**Comment by DerPopo** [comment]
It seems like it can't open the .tga or .png file you want to import for some reason. How does the file path look like (has it any special characters, is it hosted in the local network, etc)?

**Comment by kelalung** [comment]
if file data(32char) is 2300 file, this software is bug
but with 1700 file, this software is working!

**Comment by DerPopo** [comment]
Then it's because mainData depends on too many files and the function used (fopen) has a limit of 2048 opened files. I'd recommend temporarily moving around 300 files into another directory and trying again.

**Comment by kelalung** [comment]
thank you, DerPop

**Comment by MichaelPriebe** [comment]
I have around 10,000 of these. They open all fine but extracting stops working.

**Comment by DerPopo** [comment]
It silently won't open all of these and be capped at the 2048 opened files limit, so it won't be able to create a new file to extract to.
