### ISSUE TITLE
Editing .unity3d files makes them too large?

### ISSUE THREAD

**Issue by redlightnightlight** [DerPopo/UABE#94]
I want to change the Texture2D asset in a .unity3d file for a mod. (Unsure what version of Unity the file is in, but my guess is Unity 5.) But after editing the Texture2D asset in that .unity3d file and saving, the .unity3d file size increases from ~600 kB to 3128 kB, which is enough to make the game freeze and complain about running out of RAM (according to the crash logs) whenever it tries to read that .unity3d file. It is not a problem with the edit I made since I can get the game to read the .unity3d file and display the edited Texture2D asset when the game is consuming less RAM.

I have tried reducing the file size of the .png file that replaces the old Texture2D asset but, strangely, this still yields the same 3128 kB size output. Changing the texture format is not a viable option. Also, original Texture2D is about 1 MB as a png, and the png replacing it has about 1 MB as well.

Is there a way for me to edit the Texture2D asset while having a small output file size? Sorry if my wording is unclear since I am new to Unity.

**Comment by DerPopo** [comment]
It sounds like the compression mode changes. Which texture format is selected in the dialog? Unity possibly needs lots of memory to decompress the texture, I don't think that the 3 MB file itself is big enough to cause it to run out of memory. If the game runs on a PC, I'd recommend DXT1 or DXT5 (crunched takes some time to encode but makes it much smaller), on smartphones it's either EAC, ETC, PVRTC or ASTC.

**Comment by redlightnightlight** [comment]
Compressing the texture format solved it. Thanks!

**Comment by redlightnightlight** [comment]
I encountered a situation where editing the Texture2D asset of a .unity3d file and saving with either DXT5 or compressed DXT5 formats crashes the game when the asset is used. No other settings were changed when editing the Texture2D. What's strange is the Texture2D asset was originally in the DXT5 format.

What could be the issue?

**Comment by DerPopo** [comment]
Probably there are some incompatibilities with the Texture2D asset format. What exact Unity version does the game use? You can find that out with a hex editor or even with notepad and open the .unity3d or .assets file. An example for a Unity version is "5.3.1p3".

**Comment by redlightnightlight** [comment]
The game uses version 5.3.2p2.

**Comment by redlightnightlight** [comment]
I suspect the problem might be with the game itself. For example, for one .unity3d file, the game crashes if the Texture2D asset is saved as DXT5 compressed but not when it is saved as DXT5. But for another .unity3d file, the game crashes if the Texture2D asset is saved as DXT5 but not when it is saved as DXT5 compressed.

**Comment by redlightnightlight** [comment]
Another thing I noticed. Is there a way to pack a .unity3d file? It's possible the entire problem stems from the .unity3d file not being packed.

**Comment by DerPopo** [comment]
.unity3d files can't be packed at the moment. Could you try again with UABE 2.1? It fixes one issue I noticed related to saving modified UnityWeb bundles (unmodified decompressed bundles should also have worked in game before).

**Comment by redlightnightlight** [comment]
Seems like the same problem is occurring. I'll try recreating the .unity3d file in Unity with exported assets to get around the problem.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out. Feel free to open a new issue if you have further questions.
