### ISSUE TITLE
How to pack again unity3d

### ISSUE THREAD

**Issue by kelalung** [DerPopo/UABE#95]
i have 2 question! please help me!
1/ I have a file unity3d(HEADER unityweb) "call Zero", when i use uabe for this item, it show "This bundle file is compressed! do you wish to unpack it". I choose Yes , it create a new file A.!
i use uabe for file A and modify A, save A, but i dont know how to compress like Zero file!
2/ how to add new file textasset to unity3d and assets or bundle file!

**Comment by keeslient** [comment]
yeah i have the same problem too,this tool can easily unpack the unityweb header type bundle,but when i change the file and save it,the file header becomes unityraw,which makes it can't work properly.So,really hope that UABE can add a function to compress the bundle.Thanks.

**Comment by DerPopo** [comment]
So it's likely about Unity versions lower than 5.3? Afaik it should work fine uncompressed with newer versions.

**Comment by DerPopo** [comment]
Closing this one.
https://github.com/DerPopo/UABE/issues/102
