### ISSUE TITLE
Dump of MonoBehaviours

### ISSUE THREAD

**Issue by VivekDeshpande** [DerPopo/UABE#96]
Is there any way to get a readable dump of Monobehaviour assets? Currently in v2.0b if I click export dump while having a Monobehaviour selected, it throws an error "The file format is empty".

I'm trying to look and change the values that the developer has assigned on the scriptable object for a monobehaviour. Would it be possible to do so with UABE?

Screenshot of what I'm essentially asking for : 

![whatiwant](https://cloud.githubusercontent.com/assets/7048211/21565828/60386416-cec2-11e6-9d84-2226a9f56d2f.png)

**Comment by DerPopo** [comment]
The exact type information would have to be extracted from the game's assemblies, it isn't stored in the .assets file.

**Comment by VivekDeshpande** [comment]
I have been able to extract the type information from the assemblies. How do I get the data from that?

**Comment by DerPopo** [comment]
Take a look at this issue : https://github.com/DerPopo/UABE/issues/63
It should have all/most of the things covered for that task.

**Comment by OmegaRogue** [comment]
is there a plugin to extract MonoBehaviours? because i need one it is really important and no, there is nothing about these mono beahaviours in the actuall game code

**Comment by nesrak1** [comment]
I just got back to modding and I remembered a while back I had a program setup with ILSpy and a program with the UABE API that actually did this automatically although every other variable was the wrong name or something.

**Comment by DerPopo** [comment]
It'll be supported in the next release.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 is out. Feel free to open a new issue if you have further questions.
