### ISSUE TITLE
Feature request: Dump all

### ISSUE THREAD

**Issue by luckcolors** [DerPopo/UABE#98]
Hi.
When loading a .assets level or maindata file it would be very usefull to dump all of the assets (even monobehaviours) with their respective **name-pathID-fileID.type** or something along those lines ( naming the file extension after the file type that's shown in the tool would be very nice).

Also #92 would be pretty amazing to have too.
Thanks in advance! :)

**Comment by DerPopo** [comment]
Thanks for the feedback! It's added in version 2.1. Feel free to reopen the issue if you have any questions.
